// Build orchestration -- the compiler half of the former driver.c.
//
// Everything here exists to *produce* an executable: locating the toolchain
// sources, naming temporary files, and driving llc and clang. A compiled Prismio
// program never calls any of it, so this translation unit belongs in
// backend.lib / backend.a alongside llvm-api-backend.c, and never in runtime.lib.
//
// It does depend on the runtime half (prismio_runtime.h) for plain file and path
// helpers. That direction is deliberate and one-way: backend -> runtime.

#include "prismio_platform.h"
#include "prismio_runtime.h"

#ifndef PRISMIO_EMBEDDED_SOURCES_HEADER
#define PRISMIO_EMBEDDED_SOURCES_HEADER "embedded_sources.h"
#endif
#include PRISMIO_EMBEDDED_SOURCES_HEADER

// ============================================
// The toolchain source set
// ============================================

// The C sources a compiled program is linked against, plus the headers they need
// available beside them when they are unpacked from the embedded copies. Keeping
// this as one table means the filesystem search, the embedded unpacking and the
// compile/link steps can never disagree about which files make up the toolchain.
typedef struct {
    const char* name;
    int compiled;  // 1 = compile to an object and link it; 0 = header, unpack only
    const char* role;
    // 1 = part of runtime.lib, needed by every compiled program.
    // 0 = part of backend.lib, needed only when building the compiler itself.
    int runtime;
} PrismioToolchainFile;

// From llvm-api-backend.c: the target the frontend selected. Read rather than
// copied, so this file and the backend cannot disagree about what is being
// built. See the "Targets" section there.
const char* ir_target_triple(void);
int ir_target_is_explicit(void);

// M1.1's two LLVM operations. They live in llvm-api-backend.c because that is
// where the C API dependency lives; this file drives clang and does not link
// LLVM itself.
int ir_curate_module(const char* runtime_ir, const char* const* names, int count,
                     const char* out_path);
int ir_link_modules(const char* dest_ir, const char* src_ir, const char* out_path);

static const PrismioToolchainFile prismio_toolchain_files[] = {
    { "prismio_platform.h", 0, NULL,              1 },
    { "prismio_runtime.h",  0, NULL,              1 },
    { "lang_runtime.c",     1, "lang_runtime",    1 },
    { "program_support.c",  1, "program_support", 1 },
    { "build_driver.c",     1, "build_driver",    0 },
    { "ir_symbols.c",       1, "ir_symbols",      0 },
    { "aif_support.c",      1, "aif_support",     0 },
    { "diagnostics.c",      1, "diagnostics",     0 },
    { "llvm-api-backend.c", 1, "backend",         0 },
};

#define PRISMIO_TOOLCHAIN_FILE_COUNT \
    ((int)(sizeof(prismio_toolchain_files) / sizeof(prismio_toolchain_files[0])))

#ifdef PRISMIO_EMBEDDED_SOURCE_AVAILABLE
// Same order as prismio_toolchain_files. Generated by
// runtime/generate_embedded_sources.py, and checked against this table by
// tools/check_source_lists.py.
static const char* prismio_embedded_text(int index) {
    switch (index) {
        case 0: return prismio_embedded_prismio_platform_h;
        case 1: return prismio_embedded_prismio_runtime_h;
        case 2: return prismio_embedded_lang_runtime_c;
        case 3: return prismio_embedded_program_support_c;
        case 4: return prismio_embedded_build_driver_c;
        case 5: return prismio_embedded_ir_symbols_c;
        case 6: return prismio_embedded_aif_support_c;
        case 7: return prismio_embedded_diagnostics_c;
        case 8: return prismio_embedded_llvm_api_backend_c;
        default: return NULL;
    }
}
#endif

// ============================================
// Path helpers (compiler-side only)
// ============================================

static const char* path_file_name(const char* path) {
    const char* last_slash = strrchr(path, '/');
    const char* last_backslash = strrchr(path, '\\');
    const char* separator = last_slash > last_backslash ? last_slash : last_backslash;
    return separator ? separator + 1 : path;
}

static char* path_without_extension(const char* path) {
    const char* filename = path_file_name(path);
    const char* dot = strrchr(filename, '.');
    int len = dot ? (int)(dot - path) : (int)strlen(path);
    char* result = (char*)malloc(len + 1);
    strncpy(result, path, len);
    result[len] = '\0';
    return result;
}

char* compiler_default_exe_path(const char* source_path) {
    char* stem = path_without_extension(source_path);
#ifdef _WIN32
    char* result = (char*)malloc(strlen(stem) + 5);
    sprintf(result, "%s.exe", stem);
#else
    char* result = (char*)malloc(strlen(stem) + 1);
    sprintf(result, "%s", stem);
#endif
    free(stem);
    return result;
}

// Builds "<dir><sep>.prismio-<stem>-<suffix>", or the same without the directory
// prefix when the path has none. Shared by the temporary .ll, .obj and unpacked
// source directory names, which previously repeated this logic three times.
static char* compiler_temp_path(const char* base_path, const char* suffix) {
    char* directory = get_directory(base_path);
    const char* filename = path_file_name(base_path);
    const char* dot = strrchr(filename, '.');
    int stem_len = dot ? (int)(dot - filename) : (int)strlen(filename);

    int has_directory = strcmp(directory, ".") != 0;
    int result_len = (has_directory ? (int)strlen(directory) + 1 : 0) +
                     (int)strlen(".prismio-") + stem_len + 1 +
                     (int)strlen(suffix) + 1;
    char* result = (char*)malloc(result_len);

    if (has_directory) {
        sprintf(result, "%s%c.prismio-%.*s-%s", directory, PRISMIO_PATH_SEP,
                stem_len, filename, suffix);
    } else {
        sprintf(result, ".prismio-%.*s-%s", stem_len, filename, suffix);
    }

    free(directory);
    return result;
}

// LAYOUT 3.2. The workload runner needs three temporaries beside the source --
// driver IR, driver executable, and the profile itself -- and they follow the
// same ".prismio-<stem>-<suffix>" convention as every other build temporary so a
// failed build leaves recognisable litter rather than anonymous files.
//
// Unlike compiler_temp_ir_path this does *not* stamp the pid into the name. The
// profile is the one build temporary a user may want to keep and check in
// (LAYOUT 2.2: "checked in beside the manifest"), and a pid in the name would
// make that impossible to predict.
char* compiler_temp_path_for(const char* source_path, const char* suffix) {
    return compiler_temp_path(source_path, suffix);
}

// The same name with the pid in it, for a temporary that must not be shared
// between concurrent builds of one source.
//
// RESULTS-layout §7: the three paths the workload runner used were the only ones
// here without a pid, so two compiles of the same program shared one
// profile.txt. A build that read another process's profile chose a different
// field order, and -- unlike a profile that fails to load -- neither fell back
// nor warned. It made the IR differential, which is this project's definition of
// a safe change, report a false difference under any concurrent load.
//
// LAYOUT §2.2's predictable path is kept: the profile is *published* to it after
// the run (compiler_publish_file), so the artifact a user may check in beside
// the manifest still appears at the name it always had. What changed is that
// nothing reads it.
char* compiler_temp_private_path(const char* source_path, const char* suffix) {
    char stamped[128];
    snprintf(stamped, sizeof(stamped), "%d-%s", PRISMIO_GETPID(), suffix);
    return compiler_temp_path(source_path, stamped);
}

static int write_text_file(const char* path, const char* content);

// Copies `from` onto `to` through a pid-qualified temporary beside it, so a
// concurrent reader of `to` sees either the old file or the new one and never a
// half-written one. Returns 0 on success.
int compiler_publish_file(const char* from, const char* to) {
    char* text = read_file(from);
    if (!text) return 1;

    size_t len = strlen(to) + 32;
    char* tmp = (char*)malloc(len);
    snprintf(tmp, len, "%s.%d.tmp", to, PRISMIO_GETPID());

    int result = write_text_file(tmp, text);
    if (result == 0 && rename(tmp, to) != 0) {
        // Same filesystem by construction -- the temporary is a sibling -- so a
        // failure here is a permission or a disk problem, not EXDEV. Publishing
        // is best-effort either way: the build has its own copy.
        delete_file(tmp);
        result = 1;
    }

    free(tmp);
    free(text);
    return result;
}

char* compiler_temp_ir_path(const char* source_path) {
    char suffix[32];
    snprintf(suffix, sizeof(suffix), "%d.ll", PRISMIO_GETPID());
    return compiler_temp_path(source_path, suffix);
}

static char* compiler_temp_obj_path(const char* exe_file, const char* role) {
    char suffix[96];
    snprintf(suffix, sizeof(suffix), "%s-%d.obj", role, PRISMIO_GETPID());
    return compiler_temp_path(exe_file, suffix);
}

static char* compiler_temp_source_dir(const char* exe_file) {
    char suffix[64];
    snprintf(suffix, sizeof(suffix), "sources-%d", PRISMIO_GETPID());
    return compiler_temp_path(exe_file, suffix);
}

// ============================================
// Directories
// ============================================

static int ensure_directory_exists(const char* directory) {
    if (!directory || directory[0] == '\0' || strcmp(directory, ".") == 0) {
        return 0;
    }

    char* path = (char*)malloc(strlen(directory) + 1);
    strcpy(path, directory);

    int start = 0;
#ifdef _WIN32
    if (strlen(path) > 2 && path[1] == ':') {
        start = 3;
    }
#endif

    for (int i = start; path[i] != '\0'; i++) {
        if (path[i] == '/' || path[i] == '\\') {
            char saved = path[i];
            path[i] = '\0';
            if (strlen(path) > 0) {
                PRISMIO_MKDIR(path);
            }
            path[i] = saved;
        }
    }

    PRISMIO_MKDIR(path);
    free(path);
    return 0;
}

int compiler_prepare_output_path(const char* output_path) {
    char* directory = get_directory(output_path);
    int result = ensure_directory_exists(directory);
    free(directory);
    return result;
}

// ============================================
// Locating toolchain sources on disk
// ============================================

static int accept_if_exists(char* out, int out_size, const char* candidate) {
    if (!file_exists(candidate)) {
        return 0;
    }
    strncpy(out, candidate, out_size - 1);
    out[out_size - 1] = '\0';
    return 1;
}

// Looks for runtime/<filename>, first relative to the compiler executable (so an
// installed toolchain works from any working directory) and then relative to the
// current directory (so an in-repo build works).
static int find_toolchain_source(char* out, int out_size, const char* filename) {
    char candidate[1024];

    char* compiler_dir = prismio_executable_directory();
    if (compiler_dir) {
        snprintf(candidate, sizeof(candidate), "%s%c..%cruntime%c%s",
                 compiler_dir, PRISMIO_PATH_SEP, PRISMIO_PATH_SEP, PRISMIO_PATH_SEP, filename);
        if (accept_if_exists(out, out_size, candidate)) {
            free(compiler_dir);
            return 1;
        }

        snprintf(candidate, sizeof(candidate), "%s%cruntime%c%s",
                 compiler_dir, PRISMIO_PATH_SEP, PRISMIO_PATH_SEP, filename);
        if (accept_if_exists(out, out_size, candidate)) {
            free(compiler_dir);
            return 1;
        }

        free(compiler_dir);
    }

    static const char* prefixes[] = {
        "runtime\\", "runtime/",
        "..\\runtime\\", "../runtime/",
        "..\\..\\runtime\\", "../../runtime/",
        NULL
    };
    for (int i = 0; prefixes[i] != NULL; i++) {
        snprintf(candidate, sizeof(candidate), "%s%s", prefixes[i], filename);
        if (accept_if_exists(out, out_size, candidate)) {
            return 1;
        }
    }

    return 0;
}

// ============================================
// Locating the LLVM C API
//
// The backend is built on it, so a build that includes the backend needs LLVM's
// headers to compile and its C API library to link. The two places to look are
// the same two the bootstrap scripts read, in the same order and with the same
// names: PRISMIO_LLVM_DIR overrides, otherwise third_party/llvm-paths.json,
// which tools/setup_llvm.py writes. A third answer would be a third thing to
// keep in step.
// ============================================

// The value of a top-level "key": "value" pair. Not a JSON parser and does not
// pretend to be one: this reads a file this toolchain generated, whose shape is
// fixed by setup_llvm.py. The one escape a Windows path actually produces --
// a doubled backslash -- is undone; anything else is copied through, and a file
// that does not match returns 0 rather than a wrong answer.
static int json_string_field(const char* text, const char* key, char* out, int out_size) {
    char pattern[64];
    snprintf(pattern, sizeof(pattern), "\"%s\"", key);

    const char* at = strstr(text, pattern);
    if (!at) return 0;
    at = strchr(at + strlen(pattern), ':');
    if (!at) return 0;
    at = strchr(at, '"');
    if (!at) return 0;
    at++;

    int n = 0;
    while (*at && *at != '"' && n < out_size - 1) {
        if (at[0] == '\\' && (at[1] == '\\' || at[1] == '/')) at++;
        out[n++] = *at++;
    }
    if (*at != '"') return 0; // ran off the end: an incomplete value is not a value
    out[n] = '\0';
    return n > 0;
}

static int find_llvm_paths(char* include_out, int include_size, char* lib_out, int lib_size) {
    const char* root = getenv("PRISMIO_LLVM_DIR");
    if (root && root[0]) {
        snprintf(include_out, include_size, "%s%cinclude", root, PRISMIO_PATH_SEP);
        snprintf(lib_out, lib_size, "%s%clib", root, PRISMIO_PATH_SEP);
        return 1;
    }

    // Beside the compiler and then beside the working directory, matching
    // find_toolchain_source: a bootstrap runs from a checkout either way.
    static const char* relative[] = {
        "..", ".", NULL
    };
    char candidate[1024];
    char* compiler_dir = prismio_executable_directory();
    char* text = NULL;

    for (int i = 0; relative[i] && !text; i++) {
        if (!compiler_dir) break;
        snprintf(candidate, sizeof(candidate), "%s%c%s%cthird_party%cllvm-paths.json",
                 compiler_dir, PRISMIO_PATH_SEP, relative[i],
                 PRISMIO_PATH_SEP, PRISMIO_PATH_SEP);
        if (file_exists(candidate)) text = read_file(candidate);
    }
    if (compiler_dir) free(compiler_dir);

    static const char* prefixes[] = {
        "third_party/llvm-paths.json", "third_party\\llvm-paths.json",
        "../third_party/llvm-paths.json", "..\\third_party\\llvm-paths.json",
        NULL
    };
    for (int i = 0; prefixes[i] && !text; i++) {
        if (file_exists(prefixes[i])) text = read_file(prefixes[i]);
    }

    if (!text) return 0;

    int ok = json_string_field(text, "include", include_out, include_size)
          && json_string_field(text, "lib", lib_out, lib_size);
    free(text);
    return ok;
}

// ============================================
// Embedded source unpacking
// ============================================

static int write_text_file(const char* path, const char* content) {
    FILE* file = fopen(path, "wb");
    if (!file) {
        return 1;
    }
    fputs(content, file);
    fclose(file);
    return 0;
}

#ifdef PRISMIO_EMBEDDED_SOURCE_AVAILABLE
static void write_c_string_literal(FILE* file, const char* name, const char* value) {
    fprintf(file, "static const char %s[] =\n\"", name);
    int column = 0;

    for (const unsigned char* p = (const unsigned char*)value; *p; p++) {
        unsigned char c = *p;

        if (c == '\n') {
            fputs("\\n\"\n\"", file);
            column = 0;
            continue;
        }

        if (column > 96) {
            fputs("\"\n\"", file);
            column = 0;
        }

        if (c == '\\') {
            fputs("\\\\", file);
            column += 2;
        } else if (c == '"') {
            fputs("\\\"", file);
            column += 2;
        } else if (c == '\r') {
            fputs("\\r", file);
            column += 2;
        } else if (c == '\t') {
            fputs("\\t", file);
            column += 2;
        } else if (c < 32 || c > 126) {
            // Octal, because that is what C's \nnn escape means.
            fprintf(file, "\\%03o", c);
            column += 4;
        } else {
            fputc(c, file);
            column += 1;
        }
    }

    fputs("\";\n\n", file);
}

// The unpacked build_driver.c includes embedded_sources.h, so the temp directory
// needs its own copy carrying the same payload.
static int write_embedded_sources_header(const char* path) {
    FILE* file = fopen(path, "wb");
    if (!file) {
        return 1;
    }

    fputs("#ifndef PRISMIO_EMBEDDED_SOURCES_H\n", file);
    fputs("#define PRISMIO_EMBEDDED_SOURCES_H\n\n", file);
    fputs("#define PRISMIO_EMBEDDED_SOURCE_AVAILABLE 1\n\n", file);
    write_c_string_literal(file, "prismio_embedded_prismio_platform_h", prismio_embedded_prismio_platform_h);
    write_c_string_literal(file, "prismio_embedded_prismio_runtime_h", prismio_embedded_prismio_runtime_h);
    write_c_string_literal(file, "prismio_embedded_lang_runtime_c", prismio_embedded_lang_runtime_c);
    write_c_string_literal(file, "prismio_embedded_program_support_c", prismio_embedded_program_support_c);
    write_c_string_literal(file, "prismio_embedded_build_driver_c", prismio_embedded_build_driver_c);
    write_c_string_literal(file, "prismio_embedded_ir_symbols_c", prismio_embedded_ir_symbols_c);
    write_c_string_literal(file, "prismio_embedded_llvm_api_backend_c", prismio_embedded_llvm_api_backend_c);
    fputs("#endif\n", file);

    fclose(file);
    return 0;
}
#endif

// ============================================
// Installed toolchain discovery
// ============================================

// An installed toolchain looks like
//
//     <prefix>/bin/prismio(.exe)
//     <prefix>/lib/runtime.{lib,a}     linked into every compiled program
//     <prefix>/lib/backend.{lib,a}     linked into the compiler only
//     <prefix>/stdlib/
//
// and is located purely relative to the running executable: no hardcoded prefixes,
// no environment variables, no runtime sources shipped, nothing extracted from the
// binary. Also accepts lib/ sitting directly beside the executable, which is what a
// plain unpacked build tree looks like.
static int find_in_lib_dir(char* out, int out_size, const char* filename) {
    static const char* relative_dirs[] = { "..", ".", NULL };

    char* compiler_dir = prismio_executable_directory();
    if (!compiler_dir) {
        return 0;
    }

    char candidate[1024];
    for (int d = 0; relative_dirs[d] != NULL; d++) {
        snprintf(candidate, sizeof(candidate), "%s%c%s%clib%c%s",
                 compiler_dir, PRISMIO_PATH_SEP, relative_dirs[d],
                 PRISMIO_PATH_SEP, PRISMIO_PATH_SEP, filename);
        if (accept_if_exists(out, out_size, candidate)) {
            free(compiler_dir);
            return 1;
        }
    }

    free(compiler_dir);
    return 0;
}

// Accepts either archive flavour, preferring the platform-native one, so a
// toolchain packaged on one platform still resolves if copied to another.
static int find_toolchain_library(char* out, int out_size, const char* stem) {
    static const char* extensions[] = {
#ifdef _WIN32
        ".lib", ".a",
#else
        ".a", ".lib",
#endif
        NULL
    };

    char filename[256];
    for (int e = 0; extensions[e] != NULL; e++) {
        snprintf(filename, sizeof(filename), "%s%s", stem, extensions[e]);
        if (find_in_lib_dir(out, out_size, filename)) {
            return 1;
        }
    }
    return 0;
}

// The runtime archive for the target in force. `runtime.a` is the host's;
// anything else is `runtime-<triple>.a`.
//
// **This is the seam.** The compiler does not build a runtime for a foreign
// target and does not know what host functions that target has -- which module
// `print` is imported from on the web is an embedder's decision, not a
// compiler's. A framework ships runtime-wasm32-unknown-unknown.a, defines the
// host-import ABI it expects, and the compiler links whatever it is pointed at.
// Nothing is found, the build falls back to compiling the runtime sources with
// the same --target and --sysroot, which is what makes an SDK-based target like
// x86_64-apple-macos work with no archive shipped at all.
static int find_runtime_library(char* out, int out_size) {
    if (!ir_target_is_explicit()) return find_toolchain_library(out, out_size, "runtime");

    char stem[320];
    snprintf(stem, sizeof(stem), "runtime-%s", ir_target_triple());
    return find_toolchain_library(out, out_size, stem);
}

// ============================================
// Runtime freshness (FNV-1a over the runtime sources)
// ============================================

// Content hashing, not timestamps: a checkout, a copy or a touch all move mtimes
// without changing code, and mtime comparison across machines is unreliable.
// FNV-1a is implemented here rather than shelling out to shasum/certutil so the
// check has no external dependency and gives identical results on every platform.
#define PRISMIO_FNV_OFFSET 1469598103934665603ULL
#define PRISMIO_FNV_PRIME  1099511628211ULL

static unsigned long long fnv1a_bytes(unsigned long long hash, const unsigned char* data) {
    for (const unsigned char* p = data; *p; p++) {
        // Normalize line endings so a CRLF checkout hashes the same as an LF one.
        if (*p == '\r') continue;
        hash ^= (unsigned long long)(*p);
        hash *= PRISMIO_FNV_PRIME;
    }
    return hash;
}

// Hash of the sources that make up runtime.lib, in table order. Returns a malloc'd
// 16-digit hex string, or an empty string when the sources are not on disk (a
// normal installed toolchain, where there is nothing to compare against).
char* compiler_runtime_source_hash(void) {
    unsigned long long hash = PRISMIO_FNV_OFFSET;
    char path[1024];
    int hashed = 0;

    for (int i = 0; i < PRISMIO_TOOLCHAIN_FILE_COUNT; i++) {
        if (!prismio_toolchain_files[i].runtime) continue;

        if (!find_toolchain_source(path, sizeof(path), prismio_toolchain_files[i].name)) {
            char* empty = (char*)malloc(1);
            empty[0] = '\0';
            return empty;
        }

        char* text = read_file(path);
        if (!text) {
            char* empty = (char*)malloc(1);
            empty[0] = '\0';
            return empty;
        }

        // Fold the file name in too, so moving code between files is detected.
        hash = fnv1a_bytes(hash, (const unsigned char*)prismio_toolchain_files[i].name);
        hash = fnv1a_bytes(hash, (const unsigned char*)text);
        free(text);
        hashed++;
    }

    char* result = (char*)malloc(32);
    if (hashed == 0) {
        result[0] = '\0';
    } else {
        snprintf(result, 32, "%016llx", hash);
    }
    return result;
}

// The hash recorded beside the installed libraries when they were packaged.
// Empty when there is no installed toolchain or it predates hash recording.
char* compiler_installed_runtime_hash(void) {
    char path[1024];
    if (!find_in_lib_dir(path, sizeof(path), "runtime.hash")) {
        char* empty = (char*)malloc(1);
        empty[0] = '\0';
        return empty;
    }

    char* text = read_file(path);
    if (!text) {
        char* empty = (char*)malloc(1);
        empty[0] = '\0';
        return empty;
    }

    // Trim trailing whitespace the sidecar may have picked up.
    for (int i = (int)strlen(text) - 1; i >= 0; i--) {
        if (text[i] == '\n' || text[i] == '\r' || text[i] == ' ' || text[i] == '\t') {
            text[i] = '\0';
        } else {
            break;
        }
    }
    return text;
}

// ============================================
// Build orchestration
// ============================================

static int run_build_command(const char* command) {
    int result = system(command);
    return result == 0 ? 0 : 1;
}

// SPEC 7.3's `--verify`, as seen from the build.
//
// Codegen swaps the allocator and deallocator *names* and changes nothing else.
// That covers everything ir_alloc_object handed out and nothing else -- but AIF
// Level 4 made strings and lists affine, and those are allocated inside
// lang_runtime.c, past the seam. Their release would then be a pointer the
// accounting never saw, which reads as a violation on every string a program
// drops.
//
// So a verify build compiles the runtime from source with PRISMIO_AIF_VERIFY
// defined, which points its own allocator at the same shims. That keeps both
// ends of every pairing on the same side of the swap, and it keeps the property
// worth having: the *generated code* is byte-identical either way.
static int g_verify_mode = 0;

void compiler_set_verify_mode(int on) { g_verify_mode = on ? 1 : 0; }

// `-g`, as seen from the build. The DWARF itself is built by the backend and
// travels inside the .ll; this flag is the two things the *driver* has to do
// differently once it is there.
//
// **-O0 for the program object.** The rest of this file argues for -O2 and the
// measurements behind it stand, but they are measurements of speed, and -g is a
// request for a different thing. At -O2 a Prismio local is promoted out of its
// stack slot in the first hundred milliseconds of the pipeline, and every
// question a debugger can then answer about it is "optimized out". LLVM does not
// lie in that state -- it drops locations rather than keeping stale ones -- so
// the result is not wrong, it is empty, and an empty debugger is what a user
// would report as "-g does not work". Someone who wants both can still ask:
// `prismio build x.psm -O2 -g` runs the IR pipeline inside the compiler and the
// compile unit records isOptimized, so the debugger says so.
//
// **dsymutil on Darwin.** Mach-O keeps DWARF in the object file and puts only a
// debug map in the executable, so `delete_file(program_obj)` below -- which has
// always run -- would take the debug info with it. dsymutil walks the map and
// copies the DWARF into a .dSYM bundle beside the binary, which is where lldb
// looks. On ELF the linker copies the sections into the executable itself and
// there is nothing to do. This is why -g on macOS was not simply "emit the
// metadata": everything downstream of the metadata was already deleting it.
static int g_debug_info = 0;

void compiler_set_debug_info(int on) { g_debug_info = on ? 1 : 0; }

// ============================================
// Cross-compilation
//
// The triple is not stored here: llvm-api-backend.c already holds it, because
// that is where LLVM answered the question, and a second copy is a second thing
// that can be stale. This file asks.
//
// The sysroot is stored here, and is not part of the target record, because it
// is not a property of the triple -- it is where *this machine* keeps the SDK
// for it. Two hosts building the same target legitimately pass different paths,
// and the compiler has no business guessing either one: an SDK it picked itself
// is exactly the kind of "helpfully wrong" that produces a link error someone
// spends an afternoon on.
// ============================================

static char g_sysroot[1024] = "";

void compiler_set_sysroot(const char* path) {
    snprintf(g_sysroot, sizeof(g_sysroot), "%s", path ? path : "");
}

// The clang flags that name the target: either "" or a string ending in a
// space, so a caller can always paste it straight in front of the rest of the
// command. "" is the host case, where clang goes on defaulting exactly as it
// always has and every existing build is byte-for-byte unaffected.
//
// Returned in a caller-owned buffer rather than a static one: it goes into the
// object cache key, and a key built from a buffer a later call can rewrite is a
// key that describes the wrong compile.
static char* target_clang_flags(void) {
    const char* triple = ir_target_is_explicit() ? ir_target_triple() : "";
    int has_sysroot = g_sysroot[0] != '\0';
    if (!triple[0] && !has_sysroot) {
        char* empty = (char*)malloc(1);
        if (empty) empty[0] = '\0';
        return empty;
    }

    char* q_sysroot = has_sysroot ? command_quote_arg(g_sysroot) : NULL;
    int len = (int)strlen(triple) + (q_sysroot ? (int)strlen(q_sysroot) : 0) + 64;
    char* out = (char*)malloc(len);
    snprintf(out, len, "%s%s%s%s%s%s",
             triple[0] ? "--target=" : "", triple, triple[0] ? " " : "",
             has_sysroot ? "-isysroot " : "", q_sysroot ? q_sysroot : "",
             has_sysroot ? " " : "");
    if (q_sysroot) free(q_sysroot);
    return out;
}

// Whether the thing being produced is Mach-O. dsymutil is asked only of a build
// that will have a debug map to walk, and after cross-compilation that is a
// question about the *target*, not about the host this compiler is running on.
static int target_is_mach_o(void) {
    if (!ir_target_is_explicit()) {
#ifdef __APPLE__
        return 1;
#else
        return 0;
#endif
    }
    const char* t = ir_target_triple();
    return strstr(t, "apple") != NULL || strstr(t, "darwin") != NULL;
}

// LAYOUT 3.2. A workload driver calls rt_profile_*, and an *installed*
// runtime.lib may predate them -- it is a binary someone built at some point,
// and this feature is newer than some of those points. The link then fails on
// six symbols and W2 turns it into a fallback, so the effect is a workload that
// silently never runs on exactly the machines where the toolchain was installed
// rather than built.
//
// This is the same shape as the verify flag above and is here for the same
// reason: a build mode whose object code needs something the installed library
// cannot be assumed to contain must compile the runtime itself. It differs in
// one way worth stating -- verify compiles from source to change the runtime's
// *behaviour*, this one only to guarantee its *vintage*. Nothing is defined and
// the generated code is unaffected.
//
// build_from_toolchain_sources falls back to the sources embedded in the
// compiler binary when the repository is not on disk, so this costs an installed
// toolchain nothing but compile time.
static int g_workload_mode = 0;

void compiler_set_workload_mode(int on) { g_workload_mode = on ? 1 : 0; }

// IR -> object.
//
// This was `llc <ir> -filetype=obj` for a long time, and that ran the *codegen*
// pipeline only -- isel, scheduling, register allocation. llc does not run the
// IR pipeline, so mem2reg, SROA, GVN, LICM, inlining and vectorisation never
// touched a user program: every local stayed a stack slot and every field read
// was reloaded. Measured at 1.4x-3.0x across aif/corpus (RESULTS-xlang 3.1).
//
// clang runs both pipelines in one process, is already required for the link,
// and takes .ll directly -- which is why compiler_temp_ir_path spells the
// suffix `.ll`. It also drops llc from the user-build path entirely.
//
// -O2 rather than -O3: measured across the corpus, -O3 lands between 0.98x and
// 1.03x of -O2, which is noise, and costs the same compile time
// (aif/evidence/xlang/optlevel.py). -flto is speed-neutral too and worth ~15%
// of binary size, but needs linker plugin support that is not portable enough
// to make a default.
// Both live in the object-cache section below and are used here: the curated
// module is cached on the same key shape and in the same directory as the
// toolchain objects, because it is the same kind of thing -- a build product of
// the runtime sources that no program-specific input can change.
static char* object_cache_dir(void);
static char* object_cache_temp_path(const char* entry);
static int object_cache_disabled(void);
static int object_cache_trace(void);

// ============================================
// M1.1 -- the curated inlinable module
//
// Every container access in a Prismio loop is a `bl` into the separately
// compiled C runtime, and the optimiser cannot see through it. Measured, that
// seam is worth 1.03x-2.31x across the corpus and 2.00x on g2_tuned
// (aif/evidence/RESULTS-M1-lto.md).
//
// The fix is Swift's `@inlinable` spelled at IR level: take the hot container
// ops out of the runtime's own IR, rewrite their linkage to
// `available_externally` -- the body is visible to the inliner but emits no
// code -- and link that module into the program's before -O2. Calls that do not
// get inlined still resolve to the runtime archive's copy, so nothing is
// defined twice and the ordinary native link is unchanged.
//
// **Why not -flto.** It was measured and it does not work here without more
// machinery, for a reason worth recording: the backend emits program functions
// carrying no target attributes at all, while clang stamps `target-cpu` and a
// 33-entry `target-features` on every runtime function, so the LTO inliner
// answers `cost=never: conflicting attributes` before it ever prices the call.
// Making that match needs the *exact* string clang used -- a superset fails, a
// newer CPU fails, and LLVMGetHostCPUName() answers a different chip than clang
// picks on this host. Merging sidesteps all of it, because `clang -O2` on the
// merged module fills its own defaults into the attribute-less functions, and
// does so self-consistently under --target since one invocation supplies both
// halves. The merge is also faster to compile (1.18x against -flto's 1.21x and
// a whole-runtime merge's 1.88x) and needs no linker plugin.
//
// **The curated set is not a list of whatever looked hot.** A function may be
// curated only if every symbol its body references is *exported* by the runtime
// object. A `static` in lang_runtime.c is absent from that object's symbol
// table, so inlining a body that reads one produces a program referencing a
// symbol nothing defines, and the link fails with "Undefined symbols ...
// _arena_alloc_slot". That is a reproduced failure, not a worry.
// `run_curated_closure_test` asserts the property rather than trusting it.
//
// `list_push` is the case worth knowing about, because it failed the rule twice
// over and both halves had to be fixed:
//
//   1. *It referenced three `static`s* -- rt_arena_hint, arena_depth and
//      arena_alloc_slot, all reached through rt_alloc on the growth path.
//   2. *It was too big to inline anyway.* The inliner priced it at cost=675
//      against a threshold of 225 and declined at every site, so adding it to
//      this list changed nothing at all: the emitted call counts were identical
//      with and without it, and the timing differences between those two builds
//      were pure measurement noise.
//
// Outlining the growth half into `list_push_grow` fixes both at once -- it takes
// the three statics with it, and it drops the remaining fast path from 227 IR
// lines to 69. See the comment on list_push_grow in lang_runtime.c.
static const char* const PRISMIO_CURATED_OPS[] = {
    "list_get", "list_set", "list_len",
    "list_set_elem_owner", "list_set_elem_releaser",
    "rc_retain", "rc_release", "list_push",
};
#define PRISMIO_CURATED_OP_COUNT \
    ((int)(sizeof(PRISMIO_CURATED_OPS) / sizeof(PRISMIO_CURATED_OPS[0])))

// Opt-in while it is measured. Default-off means the gate can run old against
// new on one tree, and a bad result is a variable away rather than a revert.
static int inline_runtime_enabled(void) {
    const char* v = getenv("PRISMIO_INLINE_RUNTIME");
    return v && v[0] && !(v[0] == '0' && v[1] == '\0');
}

// Produce the curated module, or NULL if it cannot be produced for any reason.
//
// NULL is always safe: the caller compiles exactly as it did before. That is the
// same contract object_cache_path has, and for the same reason -- an
// optimisation that can fail a build is worse than no optimisation.
//
// Cached on the content of lang_runtime.c plus the compile flags, because the
// module is a function of both and of nothing else in the program being built.
// It is therefore produced once per toolchain per target and reused by every
// subsequent build, which is what keeps the steady-state cost at one in-process module merge.
static char* build_curated_module(const char* target_flags) {
    char lr_source[1024];
    if (!find_toolchain_source(lr_source, sizeof(lr_source), "lang_runtime.c")) return NULL;

    char* text = read_file(lr_source);
    if (!text) return NULL;

    // --verify compiles the runtime with -DPRISMIO_AIF_VERIFY, so its IR
    // differs and a module built for one mode must not serve the other. Same
    // hazard the object cache guards, same fix.
    const char* verify = g_verify_mode ? "-DPRISMIO_AIF_VERIFY " : "";

    unsigned long long hash = PRISMIO_FNV_OFFSET;
    hash = fnv1a_bytes(hash, (const unsigned char*)"curated");
    hash = fnv1a_bytes(hash, (const unsigned char*)target_flags);
    hash = fnv1a_bytes(hash, (const unsigned char*)verify);
    hash = fnv1a_bytes(hash, (const unsigned char*)text);
    for (int i = 0; i < PRISMIO_CURATED_OP_COUNT; i++) {
        hash = fnv1a_bytes(hash, (const unsigned char*)PRISMIO_CURATED_OPS[i]);
    }
    free(text);

    char* dir = object_cache_dir();
    if (!dir) return NULL;
    if (ensure_directory_exists(dir) != 0) { free(dir); return NULL; }

    char name[128];
    snprintf(name, sizeof(name), "curated-%016llx.ll", hash);
    char* entry = join_path(dir, name);
    free(dir);
    if (!entry) return NULL;

    // PRISMIO_OBJ_CACHE=0 has to reach this cache too, and for the same reason
    // it exists for the objects: the key covers the source and the flags but
    // *not* the clang that turned one into the other, so an in-place toolchain
    // upgrade leaves a stale entry that nothing notices. A bypass that skipped
    // only half the build products would be a bypass that does not bypass.
    //
    // It also makes "cold build" mean the same thing here as everywhere else,
    // which is what the compile-time measurement depends on.
    int bypass = object_cache_disabled();
    if (bypass) {
        if (object_cache_trace()) fprintf(stderr, "[objcache off] curated\n");
    } else if (file_exists(entry)) {
        if (object_cache_trace()) fprintf(stderr, "[objcache hit] curated\n");
        return entry;
    } else if (object_cache_trace()) {
        fprintf(stderr, "[objcache miss] curated\n");
    }

    // Built to a pid-qualified sibling and renamed into place, never written at
    // the cache path directly -- two builds racing on one entry would otherwise
    // link a half-written module. See object_cache_temp_path.
    char* tmp_ll = object_cache_temp_path(entry);
    char* tmp_raw = NULL;
    int failed = 0;

    {
        size_t n = strlen(tmp_ll) + 16;
        tmp_raw = (char*)malloc(n);
        if (!tmp_raw) { failed = 1; }
        else snprintf(tmp_raw, n, "%s.raw", tmp_ll);
    }

    char* q_src = failed ? NULL : command_quote_arg(lr_source);
    char* q_tmp = failed ? NULL : command_quote_arg(tmp_ll);
    char* q_raw = failed ? NULL : command_quote_arg(tmp_raw);

    if (!failed) {
        int len = (int)(strlen(q_src) + strlen(q_tmp) + strlen(q_raw)
                        + strlen(target_flags) + 256
                        + PRISMIO_CURATED_OP_COUNT * 64);
        char* command = (char*)malloc(len);
        if (!command) failed = 1;

        // 1. the runtime's own IR, at the same -O2 the runtime object is built
        //    with, so the bodies being inlined are the bodies that would have
        //    been called.
        if (!failed) {
            snprintf(command, len, "clang %s%s-O2 -Wno-deprecated-declarations -S -emit-llvm %s -o %s",
                     target_flags, verify, q_src, q_raw);
            if (run_build_command(command) != 0) failed = 1;
        }

        free(command);
    }

    // 2. the curated ops out of it, in process. Everything else is reduced to a
    //    declaration and then dropped, which is what makes the module small
    //    enough that the merge costs 1.18x rather than the whole runtime's
    //    1.88x. Byte-identical to what `llvm-extract` produced when this was a
    //    shell-out, which is how the port was checked.
    if (!failed && ir_curate_module(tmp_raw, PRISMIO_CURATED_OPS,
                                    PRISMIO_CURATED_OP_COUNT, tmp_ll) != 0) {
        failed = 1;
    }

    // A bypassed cache builds to the temporary and uses it in place; installing
    // it would repopulate the very entry the caller asked to skip.
    if (!failed && bypass) {
        free(q_src); free(q_tmp); free(q_raw);
        if (tmp_raw) { delete_file(tmp_raw); free(tmp_raw); }
        free(entry);
        return tmp_ll;
    }

    if (!failed && rename(tmp_ll, entry) != 0) {
        // A failed install is not a failed build: use the temporary this once
        // and pay for it again next time.
        free(q_src); free(q_tmp); free(q_raw);
        if (tmp_raw) { delete_file(tmp_raw); free(tmp_raw); }
        free(entry);
        return tmp_ll;
    }

    if (tmp_raw) { delete_file(tmp_raw); free(tmp_raw); }
    free(q_src); free(q_tmp); free(q_raw);

    if (failed) {
        delete_file(tmp_ll);
        free(tmp_ll);
        free(entry);
        return NULL;
    }

    free(tmp_ll);
    return entry;
}

// Merge the curated module into the program's, returning a path to the merged
// IR, or NULL to compile the program's IR unchanged.
static char* merge_curated_into_program(const char* ir_file, const char* target_flags) {
    char* curated = build_curated_module(target_flags);
    if (!curated) return NULL;

    size_t n = strlen(ir_file) + 32;
    char* merged = (char*)malloc(n);
    if (!merged) { free(curated); return NULL; }
    snprintf(merged, n, "%s.merged.ll", ir_file);

    int ok = ir_link_modules(ir_file, curated, merged) == 0;
    free(curated);

    if (!ok) {
        delete_file(merged);
        free(merged);
        return NULL;
    }
    return merged;
}

static int compile_ir_to_object(const char* ir_file, const char* program_obj) {
    char* target = target_clang_flags();

    // M1.1. Merge the curated inlinable module in before -O2, so the container
    // ops are ordinary local calls the inliner can price rather than a `bl` into
    // another translation unit.
    //
    // **Declined under -g, deliberately.** The object step drops to -O0 there,
    // and at -O0 nothing is inlined, so the merge would cost a clang invocation
    // and an llvm-link to produce identical code. Worse, it would put the
    // runtime's bodies into the module a debugger walks, which is a change to
    // what `-g` builds -- and "the merge must not silently change what -g
    // builds" is the risk this milestone was told to watch.
    char* merged = NULL;
    if (inline_runtime_enabled() && !g_debug_info) {
        merged = merge_curated_into_program(ir_file, target);
    }

    char* q_ir = command_quote_arg(merged ? merged : ir_file);
    char* q_obj = command_quote_arg(program_obj);
    int len = (int)(strlen(q_ir) + strlen(q_obj) + strlen(target) + 96);
    char* command = (char*)malloc(len);

    // --target as well as the triple already written on the module: clang needs
    // the flag to pick the right assembler and object format.
    //
    // **-Wno-override-module, and the reason it is not a papered-over bug.**
    // The clang *driver* always compiles for the SDK's deployment target --
    // arm64-apple-macosx26.0.0 here -- while a module carries at most what
    // LLVMGetDefaultTargetTriple() gives, arm64-apple-darwin25.5.0. Those never
    // match, so clang always overrides and always warns. Measured: it warns
    // identically against a module with **no triple at all**, which a plain host
    // build emits, so this was never about what we stamp and could not be fixed
    // by stamping better or by stamping nothing.
    //
    // What the warning could in principle have caught is a real ABI
    // disagreement between the triple we describe `-g` offsets against and the
    // one clang codegens for. That is worth keeping, so it is now an assertion
    // instead of a warning: run_target_test requires the data layout we stamp to
    // equal the one clang computes for the same target, for the host and for
    // wasm32. A warning on every build that everyone learns to scroll past is
    // worth less than one test that fails.
    snprintf(command, len, "clang %s-Wno-override-module %s -c %s -o %s",
             target, g_debug_info ? "-O0" : "-O2", q_ir, q_obj);
    int result = run_build_command(command);

    if (merged) {
        delete_file(merged);
        free(merged);
    }
    free(command);
    free(target);
    free(q_ir);
    free(q_obj);
    return result;
}

// Normal user mode: link the program against the runtime library and nothing else.
// backend.lib -- the LLVM C API backend, the symbol tables, the diagnostics
// engine and this file -- exists only so the compiler can
// generate code and must never end up in a user's binary.
static int link_against_runtime_library(const char* program_obj,
                                        const char* runtime_lib,
                                        const char* exe_file) {
    char* q_obj = command_quote_arg(program_obj);
    char* q_lib = command_quote_arg(runtime_lib);
    char* q_exe = command_quote_arg(exe_file);
    char* target = target_clang_flags();
    int len = (int)(strlen(q_obj) + strlen(q_lib) + strlen(q_exe) + strlen(target) + 64);
    char* command = (char*)malloc(len);

    snprintf(command, len, "clang %s%s %s -o %s", target, q_obj, q_lib, q_exe);
    int result = run_build_command(command);

    free(command);
    free(target);
    free(q_obj);
    free(q_lib);
    free(q_exe);
    return result;
}

// ============================================
// Toolchain object cache
//
// Every build compiles the toolchain sources from scratch and deletes the
// objects afterwards. Measured on this host: lang_runtime.c and
// program_support.c cost 203 ms of a 411 ms build of a 34-line program, so
// **half of every small build is recompiling code that did not change**. It is
// the same object every time -- the runtime does not depend on the program.
//
// The key is the content of the source plus the exact compile command, hashed
// with the same FNV-1a used for the staleness check above, for the reason given
// there: mtimes move on a checkout or a copy and content does not. Flags are in
// the key because `--verify` compiles the same file to a different object
// (-DPRISMIO_AIF_VERIFY), and an object built for one mode linked into the other
// is exactly the "half the allocations are outside the accounting" failure the
// verify path already guards against.
//
// **What the key does not cover: an in-place upgrade of clang itself.** The same
// source and the same flags through a different compiler produce a different
// object, and nothing here notices. Set `PRISMIO_OBJ_CACHE=0` to bypass the
// cache after a toolchain upgrade, or delete the directory. Spawning
// `clang --version` to fold into the key was measured at 28 ms -- 14% of what
// the cache saves -- and was not worth paying on every build.
// ============================================

static int object_cache_disabled(void) {
    const char* v = getenv("PRISMIO_OBJ_CACHE");
    return v && v[0] == '0' && v[1] == '\0';
}

// Prints one line per toolchain object saying whether it came from the cache.
// The test that this cache works asks for exactly this, because "the build was
// faster" is not an observation a test can make reliably on a shared host.
static int object_cache_trace(void) {
    const char* v = getenv("PRISMIO_OBJ_CACHE_TRACE");
    return v && v[0] != '\0' && !(v[0] == '0' && v[1] == '\0');
}

// PRISMIO_OBJ_CACHE_DIR *is* the directory when it is set, rather than a parent
// to append a name to. The bootstrap scripts read the same variable and use it
// directly, and two readings of one variable is how the two caches would end up
// in two places while both reporting hits.
static char* object_cache_dir(void) {
    const char* override = getenv("PRISMIO_OBJ_CACHE_DIR");
    if (override && override[0]) {
        char* copy = (char*)malloc(strlen(override) + 1);
        strcpy(copy, override);
        return copy;
    }

    const char* base;
#ifdef _WIN32
    base = getenv("TEMP");
    if (!base || !base[0]) base = getenv("TMP");
    if (!base || !base[0]) base = ".";
#else
    base = getenv("TMPDIR");
    if (!base || !base[0]) base = "/tmp";
#endif
    // Shared across every build on the host, which is the point: a test suite
    // building 119 programs compiles the runtime once rather than 119 times.
    return join_path(base, "prismio-objcache");
}

// The cache entry for one toolchain source, or NULL when the source cannot be
// read or the cache directory cannot be made. A NULL is always safe: the caller
// compiles as it did before.
static char* object_cache_path(const char* role, const char* source_path,
                               const char* command_flags,
                               const char source_paths[][1024]) {
    char* text = read_file(source_path);
    if (!text) return NULL;

    unsigned long long hash = PRISMIO_FNV_OFFSET;
    hash = fnv1a_bytes(hash, (const unsigned char*)role);
    hash = fnv1a_bytes(hash, (const unsigned char*)command_flags);
    hash = fnv1a_bytes(hash, (const unsigned char*)text);
    free(text);

    // Every header in the table, into every entry. A header changes what a .c
    // compiles to without changing a byte of it, so keying on the .c alone
    // serves an object built against the *previous* prismio_runtime.h -- and the
    // way that happens is a runtime session regenerating embedded_sources.h,
    // which is a thing this project does routinely. Over-invalidating (an edit
    // to one header rebuilds all of them) is the right side to be wrong on: the
    // headers are three files and they change rarely.
    for (int i = 0; i < PRISMIO_TOOLCHAIN_FILE_COUNT; i++) {
        if (prismio_toolchain_files[i].compiled) continue;
        if (!source_paths[i][0]) continue;
        char* header = read_file(source_paths[i]);
        if (!header) {
            // A header that cannot be read makes the key incomplete, and an
            // incomplete key is worse than no cache.
            return NULL;
        }
        hash = fnv1a_bytes(hash, (const unsigned char*)prismio_toolchain_files[i].name);
        hash = fnv1a_bytes(hash, (const unsigned char*)header);
        free(header);
    }

    // embedded_sources.h is not in the table -- it is generated, and only
    // build_driver.c includes it -- but it is a header like any other and a
    // bootstrap build compiles against it. Absent on an installed toolchain,
    // where nothing includes it either, so missing is not an incomplete key.
    char embedded[1024];
    if (find_toolchain_source(embedded, sizeof(embedded), "embedded_sources.h")) {
        char* text_h = read_file(embedded);
        if (text_h) {
            hash = fnv1a_bytes(hash, (const unsigned char*)"embedded_sources.h");
            hash = fnv1a_bytes(hash, (const unsigned char*)text_h);
            free(text_h);
        }
    }

    char* dir = object_cache_dir();
    if (ensure_directory_exists(dir) != 0) {
        free(dir);
        return NULL;
    }

    char name[128];
    snprintf(name, sizeof(name), "%s-%016llx.obj", role, hash);
    char* path = join_path(dir, name);
    free(dir);
    return path;
}

// A sibling of `entry` in the cache directory, which is where the compiler is
// told to write the object before it is renamed into place.
//
// **It has to be a sibling.** The first version compiled next to the *output
// executable* and renamed into $TMPDIR, and `rename()` cannot cross a
// filesystem: on any host where the two differ -- /tmp as tmpfs on Linux, a
// build directory on a second volume -- every install fails with EXDEV, the
// build still succeeds, and the cache silently never populates. Nothing local
// would ever have shown it, because this Mac has one volume.
static char* object_cache_temp_path(const char* entry) {
    const char* file = entry;
    for (const char* p = entry; *p; p++) {
        if (*p == '/' || *p == '\\') file = p + 1;
    }
    size_t dir_len = (size_t)(file - entry);
    size_t len = dir_len + strlen(file) + 32;
    char* tmp = (char*)malloc(len);
    snprintf(tmp, len, "%.*s.tmp-%d-%s", (int)dir_len, entry, PRISMIO_GETPID(), file);
    return tmp;
}

// Compile the toolchain from source and link it with the program.
//
// `include_backend` selects the build mode:
//   0 -- normal user build with no installed libraries beside the compiler. Only
//        the runtime half is compiled, so the result matches what linking
//        runtime.lib would have produced and the backend still cannot leak in.
//   1 -- bootstrap. The program being built *is* the compiler, so it needs the
//        backend's ir_* functions and the build orchestration in this file.
//
// `force_filesystem` refuses the copies embedded in this binary and insists on
// runtime/ on disk. Bootstrap requires it: the embedded copies were frozen when the
// *bootstrapping* compiler was built, so using them would silently link the previous
// generation's runtime into the new one and make edits to runtime/*.c invisible --
// the exact staleness chain this refactor exists to break.
static int build_from_toolchain_sources(const char* program_obj, const char* exe_file,
                                        int include_backend, int force_filesystem) {
    char source_paths[PRISMIO_TOOLCHAIN_FILE_COUNT][1024];
    char* unpacked_paths[PRISMIO_TOOLCHAIN_FILE_COUNT];
    for (int i = 0; i < PRISMIO_TOOLCHAIN_FILE_COUNT; i++) {
        source_paths[i][0] = '\0';
        unpacked_paths[i] = NULL;
    }

    int using_embedded_sources = 0;
    char* embedded_dir = NULL;
    char* embedded_header = NULL;

#ifdef PRISMIO_EMBEDDED_SOURCE_AVAILABLE
    if (!force_filesystem) {
    embedded_dir = compiler_temp_source_dir(exe_file);
    if (ensure_directory_exists(embedded_dir) == 0) {
        using_embedded_sources = 1;

        for (int i = 0; i < PRISMIO_TOOLCHAIN_FILE_COUNT && using_embedded_sources; i++) {
            if (!prismio_toolchain_files[i].runtime && !include_backend) continue;

            unpacked_paths[i] = join_path(embedded_dir, prismio_toolchain_files[i].name);
            if (write_text_file(unpacked_paths[i], prismio_embedded_text(i)) != 0) {
                using_embedded_sources = 0;
                break;
            }
            strncpy(source_paths[i], unpacked_paths[i], sizeof(source_paths[i]) - 1);
            source_paths[i][sizeof(source_paths[i]) - 1] = '\0';
        }

        // Only build_driver.c includes embedded_sources.h, so the unpacked copy is
        // needed only when the backend is part of this build.
        if (using_embedded_sources && include_backend) {
            embedded_header = join_path(embedded_dir, "embedded_sources.h");
            if (write_embedded_sources_header(embedded_header) != 0) {
                using_embedded_sources = 0;
            }
        }
    }
    }
#endif

    if (!using_embedded_sources) {
        for (int i = 0; i < PRISMIO_TOOLCHAIN_FILE_COUNT; i++) {
            if (!prismio_toolchain_files[i].runtime && !include_backend) continue;

            if (!find_toolchain_source(source_paths[i], sizeof(source_paths[i]),
                                       prismio_toolchain_files[i].name)) {
                fprintf(stderr, "ERROR: could not find runtime/%s\n",
                        prismio_toolchain_files[i].name);
                return 1;
            }
        }
    }

    // The IR is already an object by this point; compile each toolchain source and
    // link the lot together with it.
    char* q_program_obj = command_quote_arg(program_obj);
    char* q_exe = command_quote_arg(exe_file);

    char* objs[PRISMIO_TOOLCHAIN_FILE_COUNT];
    char* q_objs[PRISMIO_TOOLCHAIN_FILE_COUNT];
    // A cached object outlives this build and must not be deleted with the
    // temporaries below.
    int cached[PRISMIO_TOOLCHAIN_FILE_COUNT];
    for (int i = 0; i < PRISMIO_TOOLCHAIN_FILE_COUNT; i++) {
        objs[i] = NULL;
        q_objs[i] = NULL;
        cached[i] = 0;
    }

    // The backend half needs LLVM's headers to compile and its C API library to
    // link. Resolved once, and a failure here is fatal rather than a fallback:
    // compiling the backend against the stub declarations in prismio_llvm.h and
    // then linking without -lLLVM-C is exactly what used to happen, and it ends
    // in several hundred undefined _LLVM* symbols after a full compile.
    char llvm_include[1024] = "";
    char llvm_lib[1024] = "";
    if (include_backend && !find_llvm_paths(llvm_include, sizeof(llvm_include),
                                            llvm_lib, sizeof(llvm_lib))) {
        fprintf(stderr,
                "ERROR: no LLVM toolchain configured, and the compiler backend needs one.\n"
                "       Run: python3 tools/setup_llvm.py\n"
                "       (or set PRISMIO_LLVM_DIR to an LLVM install with include/llvm-c/Core.h)\n");
        return 1;
    }

    int command_len = 4096;
    for (int i = 0; i < PRISMIO_TOOLCHAIN_FILE_COUNT; i++) {
        command_len += (int)strlen(source_paths[i]) * 2 + 64;
    }
    command_len += (int)(strlen(q_exe) + strlen(q_program_obj));
    command_len += (int)(strlen(llvm_include) + strlen(llvm_lib)) * 2 + 256;
    char* command = (char*)malloc(command_len);
    int result = 0;

    // One flag string for every source in this build, so the cache key and the
    // command cannot disagree about what an object was compiled with.
    char* compile_flags = (char*)malloc(command_len);
    {
        char* q_include = command_quote_arg(llvm_include);
        // The unpacked or in-tree sources include each other by bare name, so
        // the directory holding them is on the include path too. `-I` on a
        // quoted path: clang takes `-I <path>` as two arguments.
        char* source_dir = get_directory(source_paths[include_backend ? 4 : 2]);
        char* q_source_dir = command_quote_arg(source_dir);
        // The target flags go in *first*, and into `compile_flags` rather than
        // into the command, so that they reach the object cache key: two
        // targets share one source and one set of -D flags, and an object built
        // for one linked into the other is a silent, genuinely nasty failure.
        char* target = target_clang_flags();
        // -g reaches the toolchain's C sources as well, so a backtrace that
        // leaves generated code does not stop at `str_concat` with no file or
        // line. Deliberately *not* paired with -O0 the way the program object is
        // (compile_ir_to_object): there, -O0 exists because a Prismio local
        // folded into a register is a local the debugger cannot print, and that
        // is the whole feature. Here what is wanted is a named frame with a
        // source line in a trace, which -O2 -g gives; building the runtime at
        // -O0 would slow every `-g` build's execution to improve inspection of
        // code nobody is stepping through. It costs compile time, not run time.
        //
        // In `compile_flags` rather than in the command, so the object cache
        // keys on it: a -g and a non-g object must not share an entry.
        snprintf(compile_flags, command_len, "%s%s-O2 -Wno-deprecated-declarations %s%s%s%s%s%s",
                 target,
                 g_debug_info ? "-g " : "",
                 g_verify_mode ? "-DPRISMIO_AIF_VERIFY " : "",
                 include_backend ? "-DPRISMIO_LLVM_REAL_HEADERS -I " : "",
                 include_backend ? q_include : "",
                 include_backend ? " -I " : "",
                 include_backend ? q_source_dir : "",
                 include_backend ? " " : "");
        free(target);
        free(q_include);
        free(q_source_dir);
        free(source_dir);
    }

    for (int i = 0; i < PRISMIO_TOOLCHAIN_FILE_COUNT && result == 0; i++) {
        if (!prismio_toolchain_files[i].compiled) continue;
        if (!prismio_toolchain_files[i].runtime && !include_backend) continue;

        const char* role = prismio_toolchain_files[i].role;
        char* entry = NULL;
        if (object_cache_disabled()) {
            // Said separately from a miss: "the cache was not consulted" and
            // "the cache was consulted and had nothing" are different facts, and
            // a bypass that reported a miss would be indistinguishable from a
            // bypass that did not bypass.
            if (object_cache_trace()) fprintf(stderr, "[objcache off] %s\n", role);
        } else {
            entry = object_cache_path(role, source_paths[i], compile_flags, source_paths);

            if (entry && file_exists(entry)) {
                if (object_cache_trace()) fprintf(stderr, "[objcache hit] %s\n", role);
                objs[i] = entry;
                q_objs[i] = command_quote_arg(entry);
                cached[i] = 1;
                continue;
            }
            if (object_cache_trace()) fprintf(stderr, "[objcache miss] %s\n", role);
        }

        // Compiled to a pid-qualified temporary *in the cache directory* and
        // moved into place, never written at the cache path directly: two builds
        // racing on one entry would otherwise link a half-written object. (The
        // profile race in runWorkloadProfile is the same mistake made the other
        // way round.) See object_cache_temp_path for why the temporary has to be
        // a sibling rather than a file beside the output.
        objs[i] = entry ? object_cache_temp_path(entry)
                        : compiler_temp_obj_path(exe_file, role);
        q_objs[i] = command_quote_arg(objs[i]);
        char* q_src = command_quote_arg(source_paths[i]);
        // -O2 here matters more than it does on the program's own IR: this is
        // where list_get, list_push and the allocator live, and a user program
        // calls them millions of times. Compiling them at -O0 was worth more of
        // the corpus gap than the missing IR pipeline was (RESULTS-xlang 3.1).
        snprintf(command, command_len, "clang %s-c %s -o %s",
                 compile_flags, q_src, q_objs[i]);
        if (run_build_command(command) != 0) result = 1;
        free(q_src);

        if (result == 0 && entry) {
            // A failed install is not a failed build: link the temporary and
            // pay for the compile again next time.
            if (rename(objs[i], entry) == 0) {
                free(objs[i]);
                free(q_objs[i]);
                objs[i] = entry;
                q_objs[i] = command_quote_arg(entry);
                cached[i] = 1;
                entry = NULL;
            }
        }
        if (entry) free(entry);
    }

    if (result == 0) {
        char* link_target = target_clang_flags();
        int written = snprintf(command, command_len, "clang %s%s", link_target, q_program_obj);
        free(link_target);
        for (int i = 0; i < PRISMIO_TOOLCHAIN_FILE_COUNT; i++) {
            if (!q_objs[i]) continue;
            written += snprintf(command + written, command_len - written, " %s", q_objs[i]);
        }
        written += snprintf(command + written, command_len - written, " -o %s", q_exe);
        if (include_backend) {
            // The half that was missing. Without it the backend's several
            // hundred LLVM calls are undefined symbols, after every object has
            // already been compiled.
            char* q_lib = command_quote_arg(llvm_lib);
            snprintf(command + written, command_len - written, " -L %s -lLLVM-C", q_lib);
            free(q_lib);
        }
        if (run_build_command(command) != 0) result = 1;
    }

    for (int i = 0; i < PRISMIO_TOOLCHAIN_FILE_COUNT; i++) {
        if (objs[i] && !cached[i]) delete_file(objs[i]);
        if (unpacked_paths[i]) delete_file(unpacked_paths[i]);
    }
    if (embedded_header) delete_file(embedded_header);
    if (embedded_dir) PRISMIO_RMDIR(embedded_dir);

    free(compile_flags);
    free(command);
    free(q_exe);
    free(q_program_obj);
    for (int i = 0; i < PRISMIO_TOOLCHAIN_FILE_COUNT; i++) {
        if (q_objs[i]) free(q_objs[i]);
        if (objs[i]) free(objs[i]);
        if (unpacked_paths[i]) free(unpacked_paths[i]);
    }
    if (embedded_header) free(embedded_header);
    if (embedded_dir) free(embedded_dir);

    return result;
}

// Mach-O only, and a warning rather than a failure if it does not work.
//
// A .dSYM is a copy of debug info that already exists somewhere else, so a
// program that built and linked is a program that runs. Failing the build
// because the bundle could not be written would turn a degraded -g into no
// binary at all. The warning names the tool so the cause is not a mystery.
static void write_dsym(const char* exe_file) {
#ifdef __APPLE__
    char* q_exe = command_quote_arg(exe_file);
    int len = (int)strlen(q_exe) + 64;
    char* command = (char*)malloc(len);
    snprintf(command, len, "dsymutil %s", q_exe);
    if (run_build_command(command) != 0) {
        fprintf(stderr,
                "warning: dsymutil failed; the binary has a debug map but no .dSYM,\n"
                "         so a debugger will find no source lines for it.\n");
    }
    free(command);
    free(q_exe);
#else
    (void)exe_file; // ELF: the linker copied the debug sections into the binary
#endif
}

// Normal user mode. The program links against the runtime only, so a link failure
// here is most often someone trying to build the compiler itself -- src/main.psm
// calls the backend's ir_* functions, which deliberately are not in runtime.lib.
int compiler_build_executable(const char* ir_file, const char* exe_file) {
    if (compiler_prepare_output_path(exe_file) != 0) {
        fprintf(stderr, "ERROR: could not create output directory\n");
        return 1;
    }

    char* program_obj = compiler_temp_obj_path(exe_file, "program");
    int result = compile_ir_to_object(ir_file, program_obj);

    if (result == 0) {
        char runtime_lib[1024];
        // An installed runtime.lib was compiled without PRISMIO_AIF_VERIFY, so a
        // verify build cannot use it: half the allocations would be outside the
        // accounting. Compiling from source is slower and this is a debug mode.
        // A workload driver skips it too, for the vintage reason at g_workload_mode.
        int have_runtime_lib = !g_verify_mode && !g_workload_mode
                               && find_runtime_library(runtime_lib, sizeof(runtime_lib));
        if (have_runtime_lib) {
            result = link_against_runtime_library(program_obj, runtime_lib, exe_file);
        } else {
            result = build_from_toolchain_sources(program_obj, exe_file, 0, 0);
        }

        if (result != 0) {
            // Two different failures, and the note that fits one is actively
            // misleading for the other.
            //
            // A *cross* build with no shipped archive fell back to compiling the
            // runtime for the named target, which needs a C library for it. With a
            // --sysroot that provides one -- an Apple SDK, say -- that works, and
            // it is how x86_64-apple-macos is built here today. With a target that
            // has no C library at all, wasm32-unknown-unknown being the case that
            // matters, it cannot: the sources stop at `#include <stdio.h>`. Telling
            // that user to run `prismio bootstrap` is nonsense -- bootstrap builds
            // a compiler for the host -- so say what was actually looked for and
            // where, by the exact name a framework has to ship it under.
            if (ir_target_is_explicit() && !have_runtime_lib) {
                fprintf(stderr,
                        "\nNOTE: no runtime library was found for --target %s, so the\n"
                        "      runtime was compiled from source for that target instead.\n"
                        "      Ship lib/runtime-%s.a beside the compiler, or pass\n"
                        "      --sysroot pointing at an SDK that provides a C library for it.\n"
                        "      A target with no C library of its own cannot be built the\n"
                        "      second way.\n",
                        ir_target_triple(), ir_target_triple());
            } else {
                fprintf(stderr,
                        "\nNOTE: a normal build links against the Prismio runtime only.\n"
                        "      If you are building the Prismio compiler itself, use:\n"
                        "          prismio bootstrap %s\n"
                        "      which also links the compiler backend (the ir_* functions)\n"
                        "      and the LLVM C API they call.\n",
                        "src/main.psm");
            }
        }
    }

    // Before the object goes away, and only while it is still there to walk. See
    // g_debug_info: on Mach-O the executable carries a debug map, not DWARF, and
    // the DWARF it points at is in the object file the next line deletes.
    if (result == 0 && g_debug_info && target_is_mach_o()) write_dsym(exe_file);

    delete_file(program_obj);
    free(program_obj);
    return result;
}

// Bootstrap / compiler-development mode.
//
// Always builds against the repository sources and never against an installed
// toolchain, so an edit to runtime/*.c shows up in the very next compiler
// generation. That guarantee is what the mode exists for, and it is why this is a
// separate entry point selected by the `bootstrap` command rather than a flag or an
// environment variable read somewhere inside the build.
//
// **This could not link a compiler between the move to the LLVM C API and
// 2026-08-17**, and nothing noticed because nothing in the tree runs it: CI and
// every session use tools/bootstrap.sh. The link line was `clang <objects> -o
// <exe>` with no `-L` and no `-lLLVM-C`, so a full compile ended in several
// hundred undefined `_LLVM*` symbols — and `compiler_build_executable` printed a
// NOTE recommending this command, which made it a signpost pointing at a trap.
//
// It resolves LLVM the same way and from the same two places the scripts do
// (find_llvm_paths), so there is one answer to "where is LLVM" rather than two
// that can drift. `run_bootstrap_command_test` builds a compiler through this
// path and requires its IR to match the one that built it, which is what stops
// the drift being silent next time.
int compiler_bootstrap_executable(const char* ir_file, const char* exe_file) {
    if (compiler_prepare_output_path(exe_file) != 0) {
        fprintf(stderr, "ERROR: could not create output directory\n");
        return 1;
    }

    char probe[1024];
    if (!find_toolchain_source(probe, sizeof(probe), "lang_runtime.c")) {
        fprintf(stderr,
                "ERROR: bootstrap needs the Prismio repository sources.\n"
                "       Could not find runtime/lang_runtime.c relative to the compiler\n"
                "       or the current directory. Run this from a Prismio checkout.\n");
        return 1;
    }

    char* program_obj = compiler_temp_obj_path(exe_file, "program");
    int result = compile_ir_to_object(ir_file, program_obj);

    if (result == 0) {
        // include_backend = 1: the artifact being produced is a compiler.
        result = build_from_toolchain_sources(program_obj, exe_file, 1, 1);
    }

    // The same reason as in compiler_build_executable, and it was missing here:
    // on Mach-O the executable carries a debug map rather than DWARF, and the
    // DWARF it points at lives in the object file the next line deletes. Without
    // this, `prismio bootstrap -g` emitted every byte of the metadata and then
    // threw away the half describing the compiler's own code -- the runtime's C
    // frames would still resolve, because their objects are in the object cache
    // and outlive the build, and a Prismio frame would not.
    if (result == 0 && g_debug_info && target_is_mach_o()) write_dsym(exe_file);

    delete_file(program_obj);
    free(program_obj);
    return result;
}

// The path in the *command* position needs more care than one in an argument
// position, which is why this does not just quote and go.
//
// On Windows, `prismio run app.psm -o build/app.exe` failed outright: cmd.exe
// reads `build/app.exe` as the command `build` with the switch `/app.exe`, even
// quoted. It then reported "Program exited with failure" -- blaming the compiled
// program for a mistake the compiler made invoking it. A forward slash in `-o`
// is a completely ordinary thing to write, so normalise instead of rejecting.
//
// Everywhere else the separator is left alone: llc and clang take forward
// slashes happily, and only the command position is parsed by the shell this way.
static char* run_command_path(const char* exe_file) {
    size_t len = strlen(exe_file);
    // Room for a leading "./" (or ".\") if the path has no directory part.
    char* path = (char*)malloc(len + 3);
    if (!path) return NULL;

    int has_separator = 0;
    for (size_t i = 0; i < len; i++) {
        if (exe_file[i] == '/' || exe_file[i] == '\\') has_separator = 1;
    }

    size_t out = 0;
    // A bare name would otherwise be looked up on PATH first, which can run a
    // different program with the same name than the one just built.
    if (!has_separator) {
        path[out++] = '.';
        path[out++] = PRISMIO_PATH_SEP;
    }

    for (size_t i = 0; i < len; i++) {
        char c = exe_file[i];
        path[out++] = (c == '/' || c == '\\') ? PRISMIO_PATH_SEP : c;
    }
    path[out] = '\0';
    return path;
}

// ============================================
// LAYOUT 3.2 -- running a workload at build time
//
// The whole of the sandbox, and it is smaller than the clause makes it sound
// because this language's surface is small. W3 names three effects to stub:
// network, absolute filesystem paths, and environment access. Prismio's runtime
// exposes none of them -- str_*, list_*, print and the allocators, and that is
// the list. What a program *can* do is declare an `extern fn` for any symbol the
// C library happens to export, which is the real hole, and it is closed on the
// other side: codegen gives every extern the runtime does not define a body of
// rt_workload_stub instead of a link (see generateWorkloadStubs). So by the time
// a driver runs, the only foreign code it can reach is the Prismio runtime.
//
// That leaves what this function owns: argv, the working directory, and time.
//
//  - **argv is empty.** cli_arg() reads the prismio_argv global, which a driver
//    never fills, so a workload cannot branch on the compiler's own command line
//    and produce a profile that depends on how the build was invoked.
//  - **The working directory is the output directory**, not the user's. A
//    relative path a workload opens through a stubbed extern goes nowhere, and
//    the profile lands beside the other build temporaries.
//  - **Time is bounded.** W2 lists "times out" as a fallback case, so it has to
//    be a case that can happen: a workload with an unbounded loop must warn and
//    fall back rather than hang the build forever.
//
// The timeout is enforced with the platform's own tool rather than by forking:
// `timeout` on Linux, and on macOS the same via a subshell watchdog, because
// coreutils' timeout is not installed by default there. A missing watchdog is
// not fatal -- the run simply is not bounded, which is the pre-existing
// behaviour of every other build command this file issues.
int compiler_run_workload(const char* exe_file, int timeout_seconds) {
    char* normalized = run_command_path(exe_file);
    if (!normalized) return 1;

    char* q_exe = command_quote_arg(normalized);
    int command_len = (int)strlen(q_exe) + 128;
    char* command = (char*)malloc(command_len);

#if defined(_WIN32)
    // No portable watchdog in cmd.exe. Recorded rather than faked: on Windows a
    // workload that hangs hangs the build, and the fix is a job object, which is
    // more platform code than this feature has earned until someone hits it.
    (void)timeout_seconds;
    snprintf(command, command_len, "%s", q_exe);
#else
    // `sh -c 'cmd & p=$!; (sleep N; kill $p) & wait $p'` is the portable form.
    // Using it unconditionally rather than probing for coreutils keeps one code
    // path on both Unixes.
    //
    // **The watchdog's redirections are load-bearing and were not obvious.** The
    // subshell inherits this process's stdout and stderr, which for any caller
    // that captures our output is a pipe. A reader waits for EOF, and EOF needs
    // *every* writer to close -- so a driver that finished in 40 ms still left
    // the reader blocked until the `sleep` expired, turning the timeout into a
    // floor on every workload build instead of a ceiling. It surfaced as the
    // test suite hanging with no process using any CPU.
    snprintf(command, command_len,
             "sh -c '%s & p=$!; { sleep %d; kill $p; } >/dev/null 2>&1 </dev/null & w=$!; "
             "wait $p; s=$?; kill $w 2>/dev/null; exit $s'",
             q_exe, timeout_seconds > 0 ? timeout_seconds : 60);
#endif

    int result = run_build_command(command);

    free(command);
    free(q_exe);
    free(normalized);
    return result;
}

int compiler_run_executable(const char* exe_file) {
    char* normalized = run_command_path(exe_file);
    if (!normalized) return 1;

    char* q_exe = command_quote_arg(normalized);
    int command_len = (int)strlen(q_exe) + 8;
    char* command = (char*)malloc(command_len);

    snprintf(command, command_len, "%s", q_exe);
    int result = run_build_command(command);

    free(command);
    free(q_exe);
    free(normalized);
    return result;
}
