// Build orchestration -- the compiler half of the former driver.c.
//
// Everything here exists to *produce* an executable: locating the toolchain
// sources, naming temporary files, and driving llc and clang. A compiled Prismio
// program never calls any of it, so this translation unit belongs in
// backend.lib / backend.a alongside llvm-api-backend.c, and never in runtime.lib.
//
// It does depend on the runtime half (prismio_runtime.h) for plain file and path
// helpers. That direction is deliberate and one-way: backend -> runtime.

#include "prismio_platform.h"
#include "prismio_runtime.h"

#ifndef PRISMIO_EMBEDDED_SOURCES_HEADER
#define PRISMIO_EMBEDDED_SOURCES_HEADER "embedded_sources.h"
#endif
#include PRISMIO_EMBEDDED_SOURCES_HEADER

// ============================================
// The toolchain source set
// ============================================

// The C sources a compiled program is linked against, plus the headers they need
// available beside them when they are unpacked from the embedded copies. Keeping
// this as one table means the filesystem search, the embedded unpacking and the
// compile/link steps can never disagree about which files make up the toolchain.
typedef struct {
    const char* name;
    int compiled;  // 1 = compile to an object and link it; 0 = header, unpack only
    const char* role;
    // 1 = part of runtime.lib, needed by every compiled program.
    // 0 = part of backend.lib, needed only when building the compiler itself.
    int runtime;
} PrismioToolchainFile;

static const PrismioToolchainFile prismio_toolchain_files[] = {
    { "prismio_platform.h", 0, NULL,              1 },
    { "prismio_runtime.h",  0, NULL,              1 },
    { "lang_runtime.c",     1, "lang_runtime",    1 },
    { "program_support.c",  1, "program_support", 1 },
    { "build_driver.c",     1, "build_driver",    0 },
    { "ir_symbols.c",       1, "ir_symbols",      0 },
    { "aif_support.c",      1, "aif_support",     0 },
    { "diagnostics.c",      1, "diagnostics",     0 },
    { "llvm-api-backend.c", 1, "backend",         0 },
};

#define PRISMIO_TOOLCHAIN_FILE_COUNT \
    ((int)(sizeof(prismio_toolchain_files) / sizeof(prismio_toolchain_files[0])))

#ifdef PRISMIO_EMBEDDED_SOURCE_AVAILABLE
// Same order as prismio_toolchain_files. Generated by
// runtime/generate_embedded_sources.py, and checked against this table by
// tools/check_source_lists.py.
static const char* prismio_embedded_text(int index) {
    switch (index) {
        case 0: return prismio_embedded_prismio_platform_h;
        case 1: return prismio_embedded_prismio_runtime_h;
        case 2: return prismio_embedded_lang_runtime_c;
        case 3: return prismio_embedded_program_support_c;
        case 4: return prismio_embedded_build_driver_c;
        case 5: return prismio_embedded_ir_symbols_c;
        case 6: return prismio_embedded_aif_support_c;
        case 7: return prismio_embedded_diagnostics_c;
        case 8: return prismio_embedded_llvm_api_backend_c;
        default: return NULL;
    }
}
#endif

// ============================================
// Path helpers (compiler-side only)
// ============================================

static const char* path_file_name(const char* path) {
    const char* last_slash = strrchr(path, '/');
    const char* last_backslash = strrchr(path, '\\');
    const char* separator = last_slash > last_backslash ? last_slash : last_backslash;
    return separator ? separator + 1 : path;
}

static char* path_without_extension(const char* path) {
    const char* filename = path_file_name(path);
    const char* dot = strrchr(filename, '.');
    int len = dot ? (int)(dot - path) : (int)strlen(path);
    char* result = (char*)malloc(len + 1);
    strncpy(result, path, len);
    result[len] = '\0';
    return result;
}

char* compiler_default_exe_path(const char* source_path) {
    char* stem = path_without_extension(source_path);
#ifdef _WIN32
    char* result = (char*)malloc(strlen(stem) + 5);
    sprintf(result, "%s.exe", stem);
#else
    char* result = (char*)malloc(strlen(stem) + 1);
    sprintf(result, "%s", stem);
#endif
    free(stem);
    return result;
}

// Builds "<dir><sep>.prismio-<stem>-<suffix>", or the same without the directory
// prefix when the path has none. Shared by the temporary .ll, .obj and unpacked
// source directory names, which previously repeated this logic three times.
static char* compiler_temp_path(const char* base_path, const char* suffix) {
    char* directory = get_directory(base_path);
    const char* filename = path_file_name(base_path);
    const char* dot = strrchr(filename, '.');
    int stem_len = dot ? (int)(dot - filename) : (int)strlen(filename);

    int has_directory = strcmp(directory, ".") != 0;
    int result_len = (has_directory ? (int)strlen(directory) + 1 : 0) +
                     (int)strlen(".prismio-") + stem_len + 1 +
                     (int)strlen(suffix) + 1;
    char* result = (char*)malloc(result_len);

    if (has_directory) {
        sprintf(result, "%s%c.prismio-%.*s-%s", directory, PRISMIO_PATH_SEP,
                stem_len, filename, suffix);
    } else {
        sprintf(result, ".prismio-%.*s-%s", stem_len, filename, suffix);
    }

    free(directory);
    return result;
}

char* compiler_temp_ir_path(const char* source_path) {
    char suffix[32];
    snprintf(suffix, sizeof(suffix), "%d.ll", PRISMIO_GETPID());
    return compiler_temp_path(source_path, suffix);
}

static char* compiler_temp_obj_path(const char* exe_file, const char* role) {
    char suffix[96];
    snprintf(suffix, sizeof(suffix), "%s-%d.obj", role, PRISMIO_GETPID());
    return compiler_temp_path(exe_file, suffix);
}

static char* compiler_temp_source_dir(const char* exe_file) {
    char suffix[64];
    snprintf(suffix, sizeof(suffix), "sources-%d", PRISMIO_GETPID());
    return compiler_temp_path(exe_file, suffix);
}

// ============================================
// Directories
// ============================================

static int ensure_directory_exists(const char* directory) {
    if (!directory || directory[0] == '\0' || strcmp(directory, ".") == 0) {
        return 0;
    }

    char* path = (char*)malloc(strlen(directory) + 1);
    strcpy(path, directory);

    int start = 0;
#ifdef _WIN32
    if (strlen(path) > 2 && path[1] == ':') {
        start = 3;
    }
#endif

    for (int i = start; path[i] != '\0'; i++) {
        if (path[i] == '/' || path[i] == '\\') {
            char saved = path[i];
            path[i] = '\0';
            if (strlen(path) > 0) {
                PRISMIO_MKDIR(path);
            }
            path[i] = saved;
        }
    }

    PRISMIO_MKDIR(path);
    free(path);
    return 0;
}

int compiler_prepare_output_path(const char* output_path) {
    char* directory = get_directory(output_path);
    int result = ensure_directory_exists(directory);
    free(directory);
    return result;
}

// ============================================
// Locating toolchain sources on disk
// ============================================

static int accept_if_exists(char* out, int out_size, const char* candidate) {
    if (!file_exists(candidate)) {
        return 0;
    }
    strncpy(out, candidate, out_size - 1);
    out[out_size - 1] = '\0';
    return 1;
}

// Looks for runtime/<filename>, first relative to the compiler executable (so an
// installed toolchain works from any working directory) and then relative to the
// current directory (so an in-repo build works).
static int find_toolchain_source(char* out, int out_size, const char* filename) {
    char candidate[1024];

    char* compiler_dir = prismio_executable_directory();
    if (compiler_dir) {
        snprintf(candidate, sizeof(candidate), "%s%c..%cruntime%c%s",
                 compiler_dir, PRISMIO_PATH_SEP, PRISMIO_PATH_SEP, PRISMIO_PATH_SEP, filename);
        if (accept_if_exists(out, out_size, candidate)) {
            free(compiler_dir);
            return 1;
        }

        snprintf(candidate, sizeof(candidate), "%s%cruntime%c%s",
                 compiler_dir, PRISMIO_PATH_SEP, PRISMIO_PATH_SEP, filename);
        if (accept_if_exists(out, out_size, candidate)) {
            free(compiler_dir);
            return 1;
        }

        free(compiler_dir);
    }

    static const char* prefixes[] = {
        "runtime\\", "runtime/",
        "..\\runtime\\", "../runtime/",
        "..\\..\\runtime\\", "../../runtime/",
        NULL
    };
    for (int i = 0; prefixes[i] != NULL; i++) {
        snprintf(candidate, sizeof(candidate), "%s%s", prefixes[i], filename);
        if (accept_if_exists(out, out_size, candidate)) {
            return 1;
        }
    }

    return 0;
}

// ============================================
// Embedded source unpacking
// ============================================

static int write_text_file(const char* path, const char* content) {
    FILE* file = fopen(path, "wb");
    if (!file) {
        return 1;
    }
    fputs(content, file);
    fclose(file);
    return 0;
}

#ifdef PRISMIO_EMBEDDED_SOURCE_AVAILABLE
static void write_c_string_literal(FILE* file, const char* name, const char* value) {
    fprintf(file, "static const char %s[] =\n\"", name);
    int column = 0;

    for (const unsigned char* p = (const unsigned char*)value; *p; p++) {
        unsigned char c = *p;

        if (c == '\n') {
            fputs("\\n\"\n\"", file);
            column = 0;
            continue;
        }

        if (column > 96) {
            fputs("\"\n\"", file);
            column = 0;
        }

        if (c == '\\') {
            fputs("\\\\", file);
            column += 2;
        } else if (c == '"') {
            fputs("\\\"", file);
            column += 2;
        } else if (c == '\r') {
            fputs("\\r", file);
            column += 2;
        } else if (c == '\t') {
            fputs("\\t", file);
            column += 2;
        } else if (c < 32 || c > 126) {
            // Octal, because that is what C's \nnn escape means.
            fprintf(file, "\\%03o", c);
            column += 4;
        } else {
            fputc(c, file);
            column += 1;
        }
    }

    fputs("\";\n\n", file);
}

// The unpacked build_driver.c includes embedded_sources.h, so the temp directory
// needs its own copy carrying the same payload.
static int write_embedded_sources_header(const char* path) {
    FILE* file = fopen(path, "wb");
    if (!file) {
        return 1;
    }

    fputs("#ifndef PRISMIO_EMBEDDED_SOURCES_H\n", file);
    fputs("#define PRISMIO_EMBEDDED_SOURCES_H\n\n", file);
    fputs("#define PRISMIO_EMBEDDED_SOURCE_AVAILABLE 1\n\n", file);
    write_c_string_literal(file, "prismio_embedded_prismio_platform_h", prismio_embedded_prismio_platform_h);
    write_c_string_literal(file, "prismio_embedded_prismio_runtime_h", prismio_embedded_prismio_runtime_h);
    write_c_string_literal(file, "prismio_embedded_lang_runtime_c", prismio_embedded_lang_runtime_c);
    write_c_string_literal(file, "prismio_embedded_program_support_c", prismio_embedded_program_support_c);
    write_c_string_literal(file, "prismio_embedded_build_driver_c", prismio_embedded_build_driver_c);
    write_c_string_literal(file, "prismio_embedded_ir_symbols_c", prismio_embedded_ir_symbols_c);
    write_c_string_literal(file, "prismio_embedded_llvm_api_backend_c", prismio_embedded_llvm_api_backend_c);
    fputs("#endif\n", file);

    fclose(file);
    return 0;
}
#endif

// ============================================
// Installed toolchain discovery
// ============================================

// An installed toolchain looks like
//
//     <prefix>/bin/prismio(.exe)
//     <prefix>/lib/runtime.{lib,a}     linked into every compiled program
//     <prefix>/lib/backend.{lib,a}     linked into the compiler only
//     <prefix>/stdlib/
//
// and is located purely relative to the running executable: no hardcoded prefixes,
// no environment variables, no runtime sources shipped, nothing extracted from the
// binary. Also accepts lib/ sitting directly beside the executable, which is what a
// plain unpacked build tree looks like.
static int find_in_lib_dir(char* out, int out_size, const char* filename) {
    static const char* relative_dirs[] = { "..", ".", NULL };

    char* compiler_dir = prismio_executable_directory();
    if (!compiler_dir) {
        return 0;
    }

    char candidate[1024];
    for (int d = 0; relative_dirs[d] != NULL; d++) {
        snprintf(candidate, sizeof(candidate), "%s%c%s%clib%c%s",
                 compiler_dir, PRISMIO_PATH_SEP, relative_dirs[d],
                 PRISMIO_PATH_SEP, PRISMIO_PATH_SEP, filename);
        if (accept_if_exists(out, out_size, candidate)) {
            free(compiler_dir);
            return 1;
        }
    }

    free(compiler_dir);
    return 0;
}

// Accepts either archive flavour, preferring the platform-native one, so a
// toolchain packaged on one platform still resolves if copied to another.
static int find_toolchain_library(char* out, int out_size, const char* stem) {
    static const char* extensions[] = {
#ifdef _WIN32
        ".lib", ".a",
#else
        ".a", ".lib",
#endif
        NULL
    };

    char filename[256];
    for (int e = 0; extensions[e] != NULL; e++) {
        snprintf(filename, sizeof(filename), "%s%s", stem, extensions[e]);
        if (find_in_lib_dir(out, out_size, filename)) {
            return 1;
        }
    }
    return 0;
}

// ============================================
// Runtime freshness (FNV-1a over the runtime sources)
// ============================================

// Content hashing, not timestamps: a checkout, a copy or a touch all move mtimes
// without changing code, and mtime comparison across machines is unreliable.
// FNV-1a is implemented here rather than shelling out to shasum/certutil so the
// check has no external dependency and gives identical results on every platform.
#define PRISMIO_FNV_OFFSET 1469598103934665603ULL
#define PRISMIO_FNV_PRIME  1099511628211ULL

static unsigned long long fnv1a_bytes(unsigned long long hash, const unsigned char* data) {
    for (const unsigned char* p = data; *p; p++) {
        // Normalize line endings so a CRLF checkout hashes the same as an LF one.
        if (*p == '\r') continue;
        hash ^= (unsigned long long)(*p);
        hash *= PRISMIO_FNV_PRIME;
    }
    return hash;
}

// Hash of the sources that make up runtime.lib, in table order. Returns a malloc'd
// 16-digit hex string, or an empty string when the sources are not on disk (a
// normal installed toolchain, where there is nothing to compare against).
char* compiler_runtime_source_hash(void) {
    unsigned long long hash = PRISMIO_FNV_OFFSET;
    char path[1024];
    int hashed = 0;

    for (int i = 0; i < PRISMIO_TOOLCHAIN_FILE_COUNT; i++) {
        if (!prismio_toolchain_files[i].runtime) continue;

        if (!find_toolchain_source(path, sizeof(path), prismio_toolchain_files[i].name)) {
            char* empty = (char*)malloc(1);
            empty[0] = '\0';
            return empty;
        }

        char* text = read_file(path);
        if (!text) {
            char* empty = (char*)malloc(1);
            empty[0] = '\0';
            return empty;
        }

        // Fold the file name in too, so moving code between files is detected.
        hash = fnv1a_bytes(hash, (const unsigned char*)prismio_toolchain_files[i].name);
        hash = fnv1a_bytes(hash, (const unsigned char*)text);
        free(text);
        hashed++;
    }

    char* result = (char*)malloc(32);
    if (hashed == 0) {
        result[0] = '\0';
    } else {
        snprintf(result, 32, "%016llx", hash);
    }
    return result;
}

// The hash recorded beside the installed libraries when they were packaged.
// Empty when there is no installed toolchain or it predates hash recording.
char* compiler_installed_runtime_hash(void) {
    char path[1024];
    if (!find_in_lib_dir(path, sizeof(path), "runtime.hash")) {
        char* empty = (char*)malloc(1);
        empty[0] = '\0';
        return empty;
    }

    char* text = read_file(path);
    if (!text) {
        char* empty = (char*)malloc(1);
        empty[0] = '\0';
        return empty;
    }

    // Trim trailing whitespace the sidecar may have picked up.
    for (int i = (int)strlen(text) - 1; i >= 0; i--) {
        if (text[i] == '\n' || text[i] == '\r' || text[i] == ' ' || text[i] == '\t') {
            text[i] = '\0';
        } else {
            break;
        }
    }
    return text;
}

// ============================================
// Build orchestration
// ============================================

static int run_build_command(const char* command) {
    int result = system(command);
    return result == 0 ? 0 : 1;
}

static int compile_ir_to_object(const char* ir_file, const char* program_obj) {
    char* q_ir = command_quote_arg(ir_file);
    char* q_obj = command_quote_arg(program_obj);
    int len = (int)(strlen(q_ir) + strlen(q_obj) + 64);
    char* command = (char*)malloc(len);

    snprintf(command, len, "llc %s -filetype=obj -o %s", q_ir, q_obj);
    int result = run_build_command(command);

    free(command);
    free(q_ir);
    free(q_obj);
    return result;
}

// Normal user mode: link the program against the runtime library and nothing else.
// backend.lib -- the LLVM C API backend, the symbol tables, the diagnostics
// engine and this file -- exists only so the compiler can
// generate code and must never end up in a user's binary.
static int link_against_runtime_library(const char* program_obj,
                                        const char* runtime_lib,
                                        const char* exe_file) {
    char* q_obj = command_quote_arg(program_obj);
    char* q_lib = command_quote_arg(runtime_lib);
    char* q_exe = command_quote_arg(exe_file);
    int len = (int)(strlen(q_obj) + strlen(q_lib) + strlen(q_exe) + 64);
    char* command = (char*)malloc(len);

    snprintf(command, len, "clang %s %s -o %s", q_obj, q_lib, q_exe);
    int result = run_build_command(command);

    free(command);
    free(q_obj);
    free(q_lib);
    free(q_exe);
    return result;
}

// Compile the toolchain from source and link it with the program.
//
// `include_backend` selects the build mode:
//   0 -- normal user build with no installed libraries beside the compiler. Only
//        the runtime half is compiled, so the result matches what linking
//        runtime.lib would have produced and the backend still cannot leak in.
//   1 -- bootstrap. The program being built *is* the compiler, so it needs the
//        backend's ir_* functions and the build orchestration in this file.
//
// `force_filesystem` refuses the copies embedded in this binary and insists on
// runtime/ on disk. Bootstrap requires it: the embedded copies were frozen when the
// *bootstrapping* compiler was built, so using them would silently link the previous
// generation's runtime into the new one and make edits to runtime/*.c invisible --
// the exact staleness chain this refactor exists to break.
static int build_from_toolchain_sources(const char* program_obj, const char* exe_file,
                                        int include_backend, int force_filesystem) {
    char source_paths[PRISMIO_TOOLCHAIN_FILE_COUNT][1024];
    char* unpacked_paths[PRISMIO_TOOLCHAIN_FILE_COUNT];
    for (int i = 0; i < PRISMIO_TOOLCHAIN_FILE_COUNT; i++) {
        source_paths[i][0] = '\0';
        unpacked_paths[i] = NULL;
    }

    int using_embedded_sources = 0;
    char* embedded_dir = NULL;
    char* embedded_header = NULL;

#ifdef PRISMIO_EMBEDDED_SOURCE_AVAILABLE
    if (!force_filesystem) {
    embedded_dir = compiler_temp_source_dir(exe_file);
    if (ensure_directory_exists(embedded_dir) == 0) {
        using_embedded_sources = 1;

        for (int i = 0; i < PRISMIO_TOOLCHAIN_FILE_COUNT && using_embedded_sources; i++) {
            if (!prismio_toolchain_files[i].runtime && !include_backend) continue;

            unpacked_paths[i] = join_path(embedded_dir, prismio_toolchain_files[i].name);
            if (write_text_file(unpacked_paths[i], prismio_embedded_text(i)) != 0) {
                using_embedded_sources = 0;
                break;
            }
            strncpy(source_paths[i], unpacked_paths[i], sizeof(source_paths[i]) - 1);
            source_paths[i][sizeof(source_paths[i]) - 1] = '\0';
        }

        // Only build_driver.c includes embedded_sources.h, so the unpacked copy is
        // needed only when the backend is part of this build.
        if (using_embedded_sources && include_backend) {
            embedded_header = join_path(embedded_dir, "embedded_sources.h");
            if (write_embedded_sources_header(embedded_header) != 0) {
                using_embedded_sources = 0;
            }
        }
    }
    }
#endif

    if (!using_embedded_sources) {
        for (int i = 0; i < PRISMIO_TOOLCHAIN_FILE_COUNT; i++) {
            if (!prismio_toolchain_files[i].runtime && !include_backend) continue;

            if (!find_toolchain_source(source_paths[i], sizeof(source_paths[i]),
                                       prismio_toolchain_files[i].name)) {
                fprintf(stderr, "ERROR: could not find runtime/%s\n",
                        prismio_toolchain_files[i].name);
                return 1;
            }
        }
    }

    // The IR is already an object by this point; compile each toolchain source and
    // link the lot together with it.
    char* q_program_obj = command_quote_arg(program_obj);
    char* q_exe = command_quote_arg(exe_file);

    char* objs[PRISMIO_TOOLCHAIN_FILE_COUNT];
    char* q_objs[PRISMIO_TOOLCHAIN_FILE_COUNT];
    for (int i = 0; i < PRISMIO_TOOLCHAIN_FILE_COUNT; i++) {
        objs[i] = NULL;
        q_objs[i] = NULL;
    }

    int command_len = 4096;
    for (int i = 0; i < PRISMIO_TOOLCHAIN_FILE_COUNT; i++) {
        command_len += (int)strlen(source_paths[i]) * 2 + 64;
    }
    command_len += (int)(strlen(q_exe) + strlen(q_program_obj));
    char* command = (char*)malloc(command_len);
    int result = 0;

    for (int i = 0; i < PRISMIO_TOOLCHAIN_FILE_COUNT && result == 0; i++) {
        if (!prismio_toolchain_files[i].compiled) continue;
        if (!prismio_toolchain_files[i].runtime && !include_backend) continue;

        objs[i] = compiler_temp_obj_path(exe_file, prismio_toolchain_files[i].role);
        q_objs[i] = command_quote_arg(objs[i]);
        char* q_src = command_quote_arg(source_paths[i]);
        snprintf(command, command_len, "clang -Wno-deprecated-declarations -c %s -o %s",
                 q_src, q_objs[i]);
        if (run_build_command(command) != 0) result = 1;
        free(q_src);
    }

    if (result == 0) {
        int written = snprintf(command, command_len, "clang %s", q_program_obj);
        for (int i = 0; i < PRISMIO_TOOLCHAIN_FILE_COUNT; i++) {
            if (!q_objs[i]) continue;
            written += snprintf(command + written, command_len - written, " %s", q_objs[i]);
        }
        snprintf(command + written, command_len - written, " -o %s", q_exe);
        if (run_build_command(command) != 0) result = 1;
    }

    for (int i = 0; i < PRISMIO_TOOLCHAIN_FILE_COUNT; i++) {
        if (objs[i]) delete_file(objs[i]);
        if (unpacked_paths[i]) delete_file(unpacked_paths[i]);
    }
    if (embedded_header) delete_file(embedded_header);
    if (embedded_dir) PRISMIO_RMDIR(embedded_dir);

    free(command);
    free(q_exe);
    free(q_program_obj);
    for (int i = 0; i < PRISMIO_TOOLCHAIN_FILE_COUNT; i++) {
        if (q_objs[i]) free(q_objs[i]);
        if (objs[i]) free(objs[i]);
        if (unpacked_paths[i]) free(unpacked_paths[i]);
    }
    if (embedded_header) free(embedded_header);
    if (embedded_dir) free(embedded_dir);

    return result;
}

// Normal user mode. The program links against the runtime only, so a link failure
// here is most often someone trying to build the compiler itself -- src/main.psm
// calls the backend's ir_* functions, which deliberately are not in runtime.lib.
int compiler_build_executable(const char* ir_file, const char* exe_file) {
    if (compiler_prepare_output_path(exe_file) != 0) {
        fprintf(stderr, "ERROR: could not create output directory\n");
        return 1;
    }

    char* program_obj = compiler_temp_obj_path(exe_file, "program");
    int result = compile_ir_to_object(ir_file, program_obj);

    if (result == 0) {
        char runtime_lib[1024];
        if (find_toolchain_library(runtime_lib, sizeof(runtime_lib), "runtime")) {
            result = link_against_runtime_library(program_obj, runtime_lib, exe_file);
        } else {
            result = build_from_toolchain_sources(program_obj, exe_file, 0, 0);
        }

        if (result != 0) {
            fprintf(stderr,
                    "\nNOTE: a normal build links against the Prismio runtime only.\n"
                    "      If you are building the Prismio compiler itself, use:\n"
                    "          prismio bootstrap %s\n"
                    "      which also links the compiler backend (the ir_* functions).\n",
                    "src/main.psm");
        }
    }

    delete_file(program_obj);
    free(program_obj);
    return result;
}

// Bootstrap / compiler-development mode.
//
// Always builds against the repository sources and never against an installed
// toolchain, so an edit to runtime/*.c shows up in the very next compiler
// generation. That guarantee is what the mode exists for, and it is why this is a
// separate entry point selected by the `bootstrap` command rather than a flag or an
// environment variable read somewhere inside the build.
int compiler_bootstrap_executable(const char* ir_file, const char* exe_file) {
    if (compiler_prepare_output_path(exe_file) != 0) {
        fprintf(stderr, "ERROR: could not create output directory\n");
        return 1;
    }

    char probe[1024];
    if (!find_toolchain_source(probe, sizeof(probe), "lang_runtime.c")) {
        fprintf(stderr,
                "ERROR: bootstrap needs the Prismio repository sources.\n"
                "       Could not find runtime/lang_runtime.c relative to the compiler\n"
                "       or the current directory. Run this from a Prismio checkout.\n");
        return 1;
    }

    char* program_obj = compiler_temp_obj_path(exe_file, "program");
    int result = compile_ir_to_object(ir_file, program_obj);

    if (result == 0) {
        // include_backend = 1: the artifact being produced is a compiler.
        result = build_from_toolchain_sources(program_obj, exe_file, 1, 1);
    }

    delete_file(program_obj);
    free(program_obj);
    return result;
}

// The path in the *command* position needs more care than one in an argument
// position, which is why this does not just quote and go.
//
// On Windows, `prismio run app.psm -o build/app.exe` failed outright: cmd.exe
// reads `build/app.exe` as the command `build` with the switch `/app.exe`, even
// quoted. It then reported "Program exited with failure" -- blaming the compiled
// program for a mistake the compiler made invoking it. A forward slash in `-o`
// is a completely ordinary thing to write, so normalise instead of rejecting.
//
// Everywhere else the separator is left alone: llc and clang take forward
// slashes happily, and only the command position is parsed by the shell this way.
static char* run_command_path(const char* exe_file) {
    size_t len = strlen(exe_file);
    // Room for a leading "./" (or ".\") if the path has no directory part.
    char* path = (char*)malloc(len + 3);
    if (!path) return NULL;

    int has_separator = 0;
    for (size_t i = 0; i < len; i++) {
        if (exe_file[i] == '/' || exe_file[i] == '\\') has_separator = 1;
    }

    size_t out = 0;
    // A bare name would otherwise be looked up on PATH first, which can run a
    // different program with the same name than the one just built.
    if (!has_separator) {
        path[out++] = '.';
        path[out++] = PRISMIO_PATH_SEP;
    }

    for (size_t i = 0; i < len; i++) {
        char c = exe_file[i];
        path[out++] = (c == '/' || c == '\\') ? PRISMIO_PATH_SEP : c;
    }
    path[out] = '\0';
    return path;
}

int compiler_run_executable(const char* exe_file) {
    char* normalized = run_command_path(exe_file);
    if (!normalized) return 1;

    char* q_exe = command_quote_arg(normalized);
    int command_len = (int)strlen(q_exe) + 8;
    char* command = (char*)malloc(command_len);

    snprintf(command, command_len, "%s", q_exe);
    int result = run_build_command(command);

    free(command);
    free(q_exe);
    free(normalized);
    return result;
}
