#ifndef PRISMIO_EMBEDDED_SOURCES_H
#define PRISMIO_EMBEDDED_SOURCES_H

#define PRISMIO_EMBEDDED_SOURCE_AVAILABLE 1

static const char prismio_embedded_runtime_c[] =
"#include <stdio.h>\n"
"#include <stdlib.h>\n"
"#include <string.h>\n"
"\n"
"#ifdef _WIN32\n"
"#include <direct.h>\n"
"#include <process.h>\n"
"#include <windows.h>\n"
"extern int __argc;\n"
"extern char** __argv;\n"
"#define PRISMIO_GETPID _getpid\n"
"#define PRISMIO_MKDIR(path) _mkdir(path)\n"
"#define PRISMIO_RMDIR(path) _rmdir(path)\n"
"#define PRISMIO_PATH_SEP '\\\\'\n"
"#else\n"
"#include <sys/stat.h>\n"
"#include <unistd.h>\n"
"#define PRISMIO_GETPID getpid\n"
"#define PRISMIO_MKDIR(path) mkdir(path, 0777)\n"
"#define PRISMIO_RMDIR(path) rmdir(path)\n"
"#define PRISMIO_PATH_SEP '/'\n"
"#endif\n"
"\n"
"#ifndef PRISMIO_EMBEDDED_SOURCES_HEADER\n"
"#define PRISMIO_EMBEDDED_SOURCES_HEADER \"embedded_sources.h\"\n"
"#endif\n"
"#include PRISMIO_EMBEDDED_SOURCES_HEADER\n"
"\n"
"// Println function - prints a string and adds a newline\n"
"void println(const char* str) {\n"
"    printf(\"%s\\n\", str);\n"
"    fflush(stdout);\n"
"}\n"
"\n"
"// Print function - prints a string without newline\n"
"void print(const char* str) {\n"
"    printf(\"%s\", str);\n"
"    fflush(stdout);\n"
"}\n"
"\n"
"// Print integer\n"
"void print_int(int value) {\n"
"    printf(\"%d\", value);\n"
"    fflush(stdout);\n"
"}\n"
"\n"
"// Print integer with newline\n"
"void println_int(int value) {\n"
"    printf(\"%d\\n\", value);\n"
"    fflush(stdout);\n"
"}\n"
"\n"
"// Print boolean\n"
"void print_bool(int value) {\n"
"    printf(\"%s\", value ? \"true\" : \"false\");\n"
"    fflush(stdout);\n"
"}\n"
"\n"
"// Print boolean with newline\n"
"void println_bool(int value) {\n"
"    printf(\"%s\\n\", value ? \"true\" : \"false\");\n"
"    fflush(stdout);\n"
"}\n"
"\n"
"// Print character\n"
"void print_char(char c) {\n"
"    printf(\"%c\", c);\n"
"    fflush(stdout);\n"
"}\n"
"\n"
"// Print character with newline\n"
"void println_char(char c) {\n"
"    printf(\"%c\\n\", c);\n"
"    fflush(stdout);\n"
"}\n"
"\n"
"// Array structure\n"
"typedef struct {\n"
"    void* data;\n"
"    int length;\n"
"    int capacity;\n"
"} Array;\n"
"\n"
"// Create array\n"
"Array* array_new(int element_size, int initial_capacity) {\n"
"    Array* arr = (Array*)malloc(sizeof(Array));\n"
"    arr->length = 0;\n"
"    arr->capacity = initial_capacity;\n"
"    arr->data = malloc(element_size * initial_capacity);\n"
"    return arr;\n"
"}\n"
"\n"
"// Free array\n"
"void array_free(Array* arr) {\n"
"    free(arr->data);\n"
"    free(arr);\n"
"}\n"
"\n"
"// Push element (generic)\n"
"void array_push(Array* arr, void* element, int element_size) {\n"
"    if (arr->length >= arr->capacity) {\n"
"        // Resize\n"
"        arr->capacity *= 2;\n"
"        arr->data = realloc(arr->data, element_size * arr->capacity);\n"
"    }\n"
"\n"
"    // Copy element to end\n"
"    char* dest = (char*)arr->data + (arr->length * element_size);\n"
"    memcpy(dest, element, element_size);\n"
"    arr->length++;\n"
"}\n"
"\n"
"// Get element\n"
"void* array_get(Array* arr, int index, int element_size) {\n"
"    if (index < 0 || index >= arr->length) {\n"
"        return NULL;\n"
"    }\n"
"    return (char*)arr->data + (index * element_size);\n"
"}\n"
"\n"
"// Array length\n"
"int array_len(Array* arr) {\n"
"    return arr->length;\n"
"}\n"
"\n"
"// ============================================\n"
"// String Comparison\n"
"// ============================================\n"
"\n"
"int str_equals(const char* s1, const char* s2) {\n"
"    return strcmp(s1, s2) == 0 ? 1 : 0;\n"
"}\n"
"\n"
"int str_compare(const char* s1, const char* s2) {\n"
"    return strcmp(s1, s2);\n"
"}\n"
"\n"
"// ============================================\n"
"// String Length\n"
"// ============================================\n"
"\n"
"int str_length(const char* s) {\n"
"    return strlen(s);\n"
"}\n"
"\n"
"// ============================================\n"
"// String Concatenation\n"
"// ============================================\n"
"\n"
"char* str_concat(const char* s1, const char* s2) {\n"
"    int len1 = strlen(s1);\n"
"    int len2 = strlen(s2);\n"
"    char* result = (char*)malloc(len1 + len2 + 1);\n"
"\n"
"    strcpy(result, s1);\n"
"    strcat(result, s2);\n"
"\n"
"    return result;\n"
"}\n"
"\n"
"// ============================================\n"
"// String Substring\n"
"// ============================================\n"
"\n"
"char* str_substring(const char* s, int start, int length) {\n"
"    int str_len = strlen(s);\n"
"\n"
"    if (start < 0 || start >= str_len) {\n"
"        return \"\";\n"
"    }\n"
"\n"
"    if (start + length > str_len) {\n"
"        length = str_len - start;\n"
"    }\n"
"\n"
"    char* result = (char*)malloc(length + 1);\n"
"    strncpy(result, s + start, length);\n"
"    result[length] = '\\0';\n"
"\n"
"    return result;\n"
"}\n"
"\n"
"// ============================================\n"
"// String Character At\n"
"// ============================================\n"
"\n"
"char str_char_at(const char* s, int index) {\n"
"    int len = strlen(s);\n"
"\n"
"    if (index < 0 || index >= len) {\n"
"        return '\\0';\n"
"    }\n"
"\n"
"    return s[index];\n"
"}\n"
"\n"
"// ============================================\n"
"// String Contains\n"
"// ============================================\n"
"\n"
"int str_contains(const char* haystack, const char* needle) {\n"
"    return strstr(haystack, needle) != NULL ? 1 : 0;\n"
"}\n"
"\n"
"// ============================================\n"
"// String Starts With\n"
"// ============================================\n"
"\n"
"int str_starts_with(const char* s, const char* prefix) {\n"
"    int s_len = strlen(s);\n"
"    int prefix_len = strlen(prefix);\n"
"\n"
"    if (prefix_len > s_len) {\n"
"        return 0;\n"
"    }\n"
"\n"
"    return strncmp(s, prefix, prefix_len) == 0 ? 1 : 0;\n"
"}\n"
"\n"
"// ============================================\n"
"// String Ends With\n"
"// ============================================\n"
"\n"
"int str_ends_with(const char* s, const char* suffix) {\n"
"    int s_len = strlen(s);\n"
"    int suffix_len = strlen(suffix);\n"
"\n"
"    if (suffix_len > s_len) {\n"
"        return 0;\n"
"    }\n"
"\n"
"    return strcmp(s + (s_len - suffix_len), suffix) == 0 ? 1 : 0;\n"
"}\n"
"\n"
"// ============================================\n"
"// String Index Of\n"
"// ============================================\n"
"\n"
"int str_index_of(const char* haystack, const char* needle) {\n"
"    const char* pos = strstr(haystack, needle);\n"
"\n"
"    if (pos == NULL) {\n"
"        return -1;\n"
"    }\n"
"\n"
"    return pos - haystack;\n"
"}\n"
"\n"
"// ============================================\n"
"// String Replace (first occurrence)\n"
"// ============================================\n"
"\n"
"char* str_replace(const char* s, const char* old_str, const char* new_str) {\n"
"    const char* pos = strstr(s, old_str);\n"
"\n"
"    if (pos == NULL) {\n"
"        // No match, return copy\n"
"        char* result = (char*)malloc(strlen(s) + 1);\n"
"        strcpy(result, s);\n"
"        return result;\n"
"    }\n"
"\n"
"    int old_len = strlen(old_str);\n"
"    int new_len = strlen(new_str);\n"
"    int prefix_len = pos - s;\n"
"    int suffix_len = strlen(pos + old_len);\n"
"\n"
"    char* result = (char*)malloc(prefix_len + new_len + suffix_len + 1);\n"
"\n"
"    // Copy prefix\n"
"    strncpy(result, s, prefix_len);\n"
"    result[prefix_len] = '\\0';\n"
"\n"
"    // Copy new string\n"
"    strcat(result, new_str);\n"
"\n"
"    // Copy suffix\n"
"    strcat(result, pos + old_len);\n"
"\n"
"    return result;\n"
"}\n"
"\n"
"// ============================================\n"
"// String To Integer\n"
"// ============================================\n"
"\n"
"int str_to_int(const char* s) {\n"
"    return atoi(s);\n"
"}\n"
"\n"
"// ============================================\n"
"// Integer To String\n"
"// ============================================\n"
"\n"
"char* int_to_str(int n) {\n"
"    char* result = (char*)malloc(32);  // enough for any int\n"
"    sprintf(result, \"%d\", n);\n"
"    return result;\n"
"}\n"
"\n"
"// ============================================\n"
"// String Clone/Copy\n"
"// ============================================\n"
"\n"
"char* str_clone(const char* s) {\n"
"    int len = strlen(s);\n"
"    char* result = (char*)malloc(len + 1);\n"
"    strcpy(result, s);\n"
"    return result;\n"
"}\n"
"\n"
"// ============================================\n"
"// String Trim (whitespace)\n"
"// ============================================\n"
"\n"
"char* str_trim(const char* s) {\n"
"    // Find start (skip leading whitespace)\n"
"    while (*s == ' ' || *s == '\\t' || *s == '\\n' || *s == '\\r') {\n"
"        s++;\n"
"    }\n"
"\n"
"    if (*s == '\\0') {\n"
"        return \"\";\n"
"    }\n"
"\n"
"    // Find end (skip trailing whitespace)\n"
"    const char* end = s + strlen(s) - 1;\n"
"    while (end > s && (*end == ' ' || *end == '\\t' || *end == '\\n' || *end == '\\r')) {\n"
"        end--;\n"
"    }\n"
"\n"
"    int len = end - s + 1;\n"
"    char* result = (char*)malloc(len + 1);\n"
"    strncpy(result, s, len);\n"
"    result[len] = '\\0';\n"
"\n"
"    return result;\n"
"}\n"
"\n"
"// ============================================\n"
"// String Split (simplified - single delimiter)\n"
"// ============================================\n"
"\n"
"typedef struct {\n"
"    char** parts;\n"
"    int count;\n"
"} StringArray;\n"
"\n"
"StringArray* str_split(const char* s, char delimiter) {\n"
"    // Count delimiters\n"
"    int count = 1;\n"
"    for (const char* p = s; *p; p++) {\n"
"        if (*p == delimiter) count++;\n"
"    }\n"
"\n"
"    StringArray* result = (StringArray*)malloc(sizeof(StringArray));\n"
"    result->parts = (char**)malloc(count * sizeof(char*));\n"
"    result->count = count;\n"
"\n"
"    int part_index = 0;\n"
"    const char* start = s;\n"
"    const char* p = s;\n"
"\n"
"    while (1) {\n"
"        if (*p == delimiter || *p == '\\0') {\n"
"            int len = p - start;\n"
"            result->parts[part_index] = (char*)malloc(len + 1);\n"
"            strncpy(result->parts[part_index], start, len);\n"
"            result->parts[part_index][len] = '\\0';\n"
"            part_index++;\n"
"\n"
"            if (*p == '\\0') break;\n"
"            start = p + 1;\n"
"        }\n"
"        p++;\n"
"    }\n"
"\n"
"    return result;\n"
"}\n"
"\n"
"void str_split_free(StringArray* arr) {\n"
"    for (int i = 0; i < arr->count; i++) {\n"
"        free(arr->parts[i]);\n"
"    }\n"
"    free(arr->parts);\n"
"    free(arr);\n"
"}\n"
"\n"
"// ============================================\n"
"// File I/O Functions\n"
"// ============================================\n"
"\n"
"// Check if file exists\n"
"int file_exists(const char* path) {\n"
"    FILE* file = fopen(path, \"r\");\n"
"    if (file) {\n"
"        fclose(file);\n"
"        return 1;\n"
"    }\n"
"    return 0;\n"
"}\n"
"\n"
"// Read entire file into string\n"
"char* read_file(const char* path) {\n"
"    FILE* file = fopen(path, \"rb\");\n"
"    if (!file) {\n"
"        return NULL;\n"
"    }\n"
"\n"
"    // Get file size\n"
"    fseek(file, 0, SEEK_END);\n"
"    long size = ftell(file);\n"
"    fseek(file, 0, SEEK_SET);\n"
"\n"
"    // Allocate buffer\n"
"    char* buffer = (char*)malloc(size + 1);\n"
"    if (!buffer) {\n"
"        fclose(file);\n"
"        return NULL;\n"
"    }\n"
"\n"
"    // Read file\n"
"    size_t read = fread(buffer, 1, size, file);\n"
"    buffer[read] = '\\0';\n"
"\n"
"    fclose(file);\n"
"    return buffer;\n"
"}\n"
"\n"
"// Get directory from file path\n"
"char* get_directory(const char* path) {\n"
"    const char* last_slash = strrchr(path, '/');\n"
"    const char* last_backslash = strrchr(path, '\\\\');\n"
"\n"
"    const char* separator = last_slash > last_backslash ? last_slash : last_backslash;\n"
"\n"
"    if (!separator) {\n"
"        char* result = (char*)malloc(2);\n"
"        strcpy(result, \".\");\n"
"        return result;\n"
"    }\n"
"\n"
"    int len = separator - path;\n"
"    char* result = (char*)malloc(len + 1);\n"
"    strncpy(result, path, len);\n"
"    result[len] = '\\0';\n"
"\n"
"    return result;\n"
"}\n"
"\n"
"static const char* path_file_name(const char* path) {\n"
"    const char* last_slash = strrchr(path, '/');\n"
"    const char* last_backslash = strrchr(path, '\\\\');\n"
"    const char* separator = last_slash > last_backslash ? last_slash : last_backslash;\n"
"    return separator ? separator + 1 : path;\n"
"}\n"
"\n"
"static char* path_without_extension(const char* path) {\n"
"    const char* filename = path_file_name(path);\n"
"    const char* dot = strrchr(filename, '.');\n"
"    int len = dot ? (int)(dot - path) : (int)strlen(path);\n"
"    char* result = (char*)malloc(len + 1);\n"
"    strncpy(result, path, len);\n"
"    result[len] = '\\0';\n"
"    return result;\n"
"}\n"
"\n"
"char* compiler_default_exe_path(const char* source_path) {\n"
"    char* stem = path_without_extension(source_path);\n"
"    char* result = (char*)malloc(strlen(stem) + 5);\n"
"    sprintf(result, \"%s.exe\", stem);\n"
"    free(stem);\n"
"    return result;\n"
"}\n"
"\n"
"char* compiler_temp_ir_path(const char* source_path) {\n"
"    char* directory = get_directory(source_path);\n"
"    const char* filename = path_file_name(source_path);\n"
"    const char* dot = strrchr(filename, '.');\n"
"    int stem_len = dot ? (int)(dot - filename) : (int)strlen(filename);\n"
"    int pid = PRISMIO_GETPID();\n"
"\n"
"    int has_directory = strcmp(directory, \".\") != 0;\n"
"    int result_len = (has_directory ? (int)strlen(directory) + 1 : 0) +\n"
"                     (int)strlen(\".prismio-\") + stem_len +\n"
"                     (int)strlen(\"-2147483648.ll\") + 1;\n"
"    char* result = (char*)malloc(result_len);\n"
"\n"
"    if (has_directory) {\n"
"        sprintf(result, \"%s%c.prismio-%.*s-%d.ll\", directory,\n"
"#ifdef _WIN32\n"
"                '\\\\',\n"
"#else\n"
"                '/',\n"
"#endif\n"
"                stem_len, filename, pid);\n"
"    } else {\n"
"        sprintf(result, \".prismio-%.*s-%d.ll\", stem_len, filename, pid);\n"
"    }\n"
"\n"
"    free(directory);\n"
"    return result;\n"
"}\n"
"\n"
"int delete_file(const char* path) {\n"
"    if (!path || path[0] == '\\0') return 0;\n"
"    return remove(path) == 0 ? 0 : 1;\n"
"}\n"
"\n"
"static int ensure_directory_exists(const char* directory) {\n"
"    if (!directory || directory[0] == '\\0' || strcmp(directory, \".\") == 0) {\n"
"        return 0;\n"
"    }\n"
"\n"
"    char* path = (char*)malloc(strlen(directory) + 1);\n"
"    strcpy(path, directory);\n"
"\n"
"    int start = 0;\n"
"#ifdef _WIN32\n"
"    if (strlen(path) > 2 && path[1] == ':') {\n"
"        start = 3;\n"
"    }\n"
"#endif\n"
"\n"
"    for (int i = start; path[i] != '\\0'; i++) {\n"
"        if (path[i] == '/' || path[i] == '\\\\') {\n"
"            char saved = path[i];\n"
"            path[i] = '\\0';\n"
"            if (strlen(path) > 0) {\n"
"                PRISMIO_MKDIR(path);\n"
"            }\n"
"            path[i] = saved;\n"
"        }\n"
"    }\n"
"\n"
"    PRISMIO_MKDIR(path);\n"
"    free(path);\n"
"    return 0;\n"
"}\n"
"\n"
"int compiler_prepare_output_path(const char* output_path) {\n"
"    char* directory = get_directory(output_path);\n"
"    int result = ensure_directory_exists(directory);\n"
"    free(directory);\n"
"    return result;\n"
"}\n"
"\n"
"static int copy_existing_path(char* out, int out_size, const char** candidates) {\n"
"    for (int i = 0; candidates[i] != NULL; i++) {\n"
"        FILE* file = fopen(candidates[i], \"rb\");\n"
"        if (file) {\n"
"            fclose(file);\n"
"            strncpy(out, candidates[i], out_size - 1);\n"
"            out[out_size - 1] = '\\0';\n"
"            return 1;\n"
"        }\n"
"    }\n"
"    return 0;\n"
"}\n"
"\n"
"static int copy_existing_file_path(char* out, int out_size, const char* candidate) {\n"
"    FILE* file = fopen(candidate, \"rb\");\n"
"    if (file) {\n"
"        fclose(file);\n"
"        strncpy(out, candidate, out_size - 1);\n"
"        out[out_size - 1] = '\\0';\n"
"        return 1;\n"
"    }\n"
"    return 0;\n"
"}\n"
"\n"
"static char* compiler_executable_directory() {\n"
"#ifdef _WIN32\n"
"    char exe_path[1024];\n"
"    DWORD len = GetModuleFileNameA(NULL, exe_path, sizeof(exe_path));\n"
"    if (len > 0 && len < sizeof(exe_path)) {\n"
"        return get_directory(exe_path);\n"
"    }\n"
"\n"
"    if (__argc > 0 && __argv[0] && __argv[0][0] != '\\0') {\n"
"        return get_directory(__argv[0]);\n"
"    }\n"
"#else\n"
"    char exe_path[1024];\n"
"    ssize_t len = readlink(\"/proc/self/exe\", exe_path, sizeof(exe_path) - 1);\n"
"    if (len > 0) {\n"
"        exe_path[len] = '\\0';\n"
"        return get_directory(exe_path);\n"
"    }\n"
"#endif\n"
"    return NULL;\n"
"}\n"
"\n"
"char* executable_directory() {\n"
"    char* directory = compiler_executable_directory();\n"
"    if (directory) {\n"
"        return directory;\n"
"    }\n"
"\n"
"    char* fallback = (char*)malloc(2);\n"
"    strcpy(fallback, \".\");\n"
"    return fallback;\n"
"}\n"
"\n"
"static int copy_toolchain_source_path(char* out, int out_size, const char* filename, const char** cwd_candidates) {\n"
"    char* compiler_dir = compiler_executable_directory();\n"
"    if (compiler_dir) {\n"
"        char candidate[1024];\n"
"\n"
"        snprintf(candidate, sizeof(candidate), \"%s%c..%cruntime%c%s\",\n"
"                 compiler_dir, PRISMIO_PATH_SEP, PRISMIO_PATH_SEP, PRISMIO_PATH_SEP, filename);\n"
"        if (copy_existing_file_path(out, out_size, candidate)) {\n"
"            free(compiler_dir);\n"
"            return 1;\n"
"        }\n"
"\n"
"        snprintf(candidate, sizeof(candidate), \"%s%cruntime%c%s\",\n"
"                 compiler_dir, PRISMIO_PATH_SEP, PRISMIO_PATH_SEP, filename);\n"
"        if (copy_existing_file_path(out, out_size, candidate)) {\n"
"            free(compiler_dir);\n"
"            return 1;\n"
"        }\n"
"\n"
"        free(compiler_dir);\n"
"    }\n"
"\n"
"    return copy_existing_path(out, out_size, cwd_candidates);\n"
"}\n"
"\n"
"static char* quote_arg(const char* arg) {\n"
"    int len = strlen(arg);\n"
"    char* result = (char*)malloc((len * 2) + 3);\n"
"    int out = 0;\n"
"    result[out++] = '\"';\n"
"    for (int i = 0; i < len; i++) {\n"
"        if (arg[i] == '\"') {\n"
"            result[out++] = '\\\\';\n"
"        }\n"
"        result[out++] = arg[i];\n"
"    }\n"
"    result[out++] = '\"';\n"
"    result[out] = '\\0';\n"
"    return result;\n"
"}\n"
"\n"
"char* command_quote_arg(const char* arg) {\n"
"    return quote_arg(arg);\n"
"}\n"
"\n"
"static int run_build_command(const char* command) {\n"
"    int result = system(command);\n"
"    return result == 0 ? 0 : 1;\n"
"}\n"
"\n"
"int execute_command(const char* command) {\n"
"#ifdef _WIN32\n"
"    int command_len = (int)strlen(command) + 16;\n"
"    char* wrapped = (char*)malloc(command_len);\n"
"    snprintf(wrapped, command_len, \"cmd /S /C \\\"%s\\\"\", command);\n"
"    int result = run_build_command(wrapped);\n"
"    free(wrapped);\n"
"    return result;\n"
"#else\n"
"    return run_build_command(command);\n"
"#endif\n"
"}\n"
"\n"
"static char* compiler_temp_obj_path(const char* exe_file, const char* role) {\n"
"    char* directory = get_directory(exe_file);\n"
"    const char* filename = path_file_name(exe_file);\n"
"    const char* dot = strrchr(filename, '.');\n"
"    int stem_len = dot ? (int)(dot - filename) : (int)strlen(filename);\n"
"    int pid = PRISMIO_GETPID();\n"
"    int has_directory = strcmp(directory, \".\") != 0;\n"
"    int result_len = (has_directory ? (int)strlen(directory) + 1 : 0) +\n"
"                     (int)strlen(\".prismio-\") + stem_len + 1 +\n"
"                     (int)strlen(role) + (int)strlen(\"-2147483648.obj\") + 1;\n"
"    char* result = (char*)malloc(result_len);\n"
"\n"
"    if (has_directory) {\n"
"        sprintf(result, \"%s%c.prismio-%.*s-%s-%d.obj\", directory,\n"
"#ifdef _WIN32\n"
"                '\\\\',\n"
"#else\n"
"                '/',\n"
"#endif\n"
"                stem_len, filename, role, pid);\n"
"    } else {\n"
"        sprintf(result, \".prismio-%.*s-%s-%d.obj\", stem_len, filename, role, pid);\n"
"    }\n"
"\n"
"    free(directory);\n"
"    return result;\n"
"}\n"
"\n"
"static char* compiler_temp_source_dir(const char* exe_file) {\n"
"    char* directory = get_directory(exe_file);\n"
"    const char* filename = path_file_name(exe_file);\n"
"    const char* dot = strrchr(filename, '.');\n"
"    int stem_len = dot ? (int)(dot - filename) : (int)strlen(filename);\n"
"    int pid = PRISMIO_GETPID();\n"
"    int has_directory = strcmp(directory, \".\") != 0;\n"
"    int result_len = (has_directory ? (int)strlen(directory) + 1 : 0) +\n"
"                     (int)strlen(\".prismio-\") + stem_len +\n"
"                     (int)strlen(\"-sources-2147483648\") + 1;\n"
"    char* result = (char*)malloc(result_len);\n"
"\n"
"    if (has_directory) {\n"
"        sprintf(result, \"%s%c.prismio-%.*s-sources-%d\",\n"
"                directory, PRISMIO_PATH_SEP, stem_len, filename, pid);\n"
"    } else {\n"
"        sprintf(result, \".prismio-%.*s-sources-%d\", stem_len, filename, pid);\n"
"    }\n"
"\n"
"    free(directory);\n"
"    return result;\n"
"}\n"
"\n"
"static char* path_join(const char* directory, const char* filename) {\n"
"    int len = (int)strlen(directory) + 1 + (int)strlen(filename) + 1;\n"
"    char* result = (char*)malloc(len);\n"
"    sprintf(result, \"%s%c%s\", directory, PRISMIO_PATH_SEP, filename);\n"
"    return result;\n"
"}\n"
"\n"
"char* join_path(const char* directory, const char* filename) {\n"
"    return path_join(directory, filename);\n"
"}\n"
"\n"
"static int write_text_file(const char* path, const char* content) {\n"
"    FILE* file = fopen(path, \"wb\");\n"
"    if (!file) {\n"
"        return 1;\n"
"    }\n"
"    fputs(content, file);\n"
"    fclose(file);\n"
"    return 0;\n"
"}\n"
"\n"
"static void write_c_string_literal(FILE* file, const char* name, const char* value) {\n"
"    fprintf(file, \"static const char %s[] =\\n\\\"\", name);\n"
"    int column = 0;\n"
"\n"
"    for (const unsigned char* p = (const unsigned char*)value; *p; p++) {\n"
"        unsigned char c = *p;\n"
"\n"
"        if (c == '\\n') {\n"
"            fputs(\"\\\\n\\\"\\n\\\"\", file);\n"
"            column = 0;\n"
"            continue;\n"
"        }\n"
"\n"
"        if (column > 96) {\n"
"            fputs(\"\\\"\\n\\\"\", file);\n"
"            column = 0;\n"
"        }\n"
"\n"
"        if (c == '\\\\') {\n"
"            fputs(\"\\\\\\\\\", file);\n"
"            column += 2;\n"
"        } else if (c == '\"') {\n"
"            fputs(\"\\\\\\\"\", file);\n"
"            column += 2;\n"
"        } else if (c == '\\r') {\n"
"            fputs(\"\\\\r\", file);\n"
"            column += 2;\n"
"        } else if (c == '\\t') {\n"
"            fputs(\"\\\\t\", file);\n"
"            column += 2;\n"
"        } else if (c < 32 || c > 126) {\n"
"            fprintf(file, \"\\\\%03o\", c);\n"
"            column += 4;\n"
"        } else {\n"
"            fputc(c, file);\n"
"            column += 1;\n"
"        }\n"
"    }\n"
"\n"
"    fputs(\"\\\";\\n\\n\", file);\n"
"}\n"
"\n"
"static int write_embedded_sources_header(const char* path) {\n"
"    FILE* file = fopen(path, \"wb\");\n"
"    if (!file) {\n"
"        return 1;\n"
"    }\n"
"\n"
"    fputs(\"#ifndef PRISMIO_EMBEDDED_SOURCES_H\\n\", file);\n"
"    fputs(\"#define PRISMIO_EMBEDDED_SOURCES_H\\n\\n\", file);\n"
"    fputs(\"#define PRISMIO_EMBEDDED_SOURCE_AVAILABLE 1\\n\\n\", file);\n"
"    write_c_string_literal(file, \"prismio_embedded_runtime_c\", prismio_embedded_runtime_c);\n"
"    write_c_string_literal(file, \"prismio_embedded_llvm_bridge_c\", prismio_embedded_llvm_bridge_c);\n"
"    fputs(\"#endif\\n\", file);\n"
"\n"
"    fclose(file);\n"
"    return 0;\n"
"}\n"
"\n"
"int compiler_build_executable(const char* ir_file, const char* exe_file) {\n"
"    const char* runtime_candidates[] = {\n"
"        \"runtime\\\\runtime.c\", \"runtime/runtime.c\",\n"
"        \"..\\\\runtime\\\\runtime.c\", \"../runtime/runtime.c\",\n"
"        \"..\\\\..\\\\runtime\\\\runtime.c\", \"../../runtime/runtime.c\",\n"
"        NULL\n"
"    };\n"
"    const char* bridge_candidates[] = {\n"
"        \"runtime\\\\llvm-bridge.c\", \"runtime/llvm-bridge.c\",\n"
"        \"..\\\\runtime\\\\llvm-bridge.c\", \"../runtime/llvm-bridge.c\",\n"
"        \"..\\\\..\\\\runtime\\\\llvm-bridge.c\", \"../../runtime/llvm-bridge.c\",\n"
"        NULL\n"
"    };\n"
"\n"
"    if (compiler_prepare_output_path(exe_file) != 0) {\n"
"        fprintf(stderr, \"ERROR: could not create output directory\\n\");\n"
"        return 1;\n"
"    }\n"
"\n"
"    char runtime_c[1024];\n"
"    char bridge_c[1024];\n"
"    int using_embedded_sources = 0;\n"
"    char* embedded_dir = NULL;\n"
"    char* embedded_runtime_c = NULL;\n"
"    char* embedded_bridge_c = NULL;\n"
"    char* embedded_header = NULL;\n"
"\n"
"#ifdef PRISMIO_EMBEDDED_SOURCE_AVAILABLE\n"
"    embedded_dir = compiler_temp_source_dir(exe_file);\n"
"    embedded_runtime_c = path_join(embedded_dir, \"runtime.c\");\n"
"    embedded_bridge_c = path_join(embedded_dir, \"llvm-bridge.c\");\n"
"    embedded_header = path_join(embedded_dir, \"embedded_sources.h\");\n"
"\n"
"    if (ensure_directory_exists(embedded_dir) == 0 &&\n"
"        write_text_file(embedded_runtime_c, prismio_embedded_runtime_c) == 0 &&\n"
"        write_text_file(embedded_bridge_c, prismio_embedded_llvm_bridge_c) == 0 &&\n"
"        write_embedded_sources_header(embedded_header) == 0) {\n"
"        strncpy(runtime_c, embedded_runtime_c, sizeof(runtime_c) - 1);\n"
"        runtime_c[sizeof(runtime_c) - 1] = '\\0';\n"
"        strncpy(bridge_c, embedded_bridge_c, sizeof(bridge_c) - 1);\n"
"        bridge_c[sizeof(bridge_c) - 1] = '\\0';\n"
"        using_embedded_sources = 1;\n"
"    }\n"
"#endif\n"
"\n"
"    if (!using_embedded_sources && !copy_toolchain_source_path(runtime_c, sizeof(runtime_c), \"runtime.c\", runtime_candidates)) {\n"
"        fprintf(stderr, \"ERROR: could not find runtime/runtime.c\\n\");\n"
"        return 1;\n"
"    }\n"
"\n"
"    if (!using_embedded_sources && !copy_toolchain_source_path(bridge_c, sizeof(bridge_c), \"llvm-bridge.c\", bridge_candidates)) {\n"
"        fprintf(stderr, \"ERROR: could not find runtime/llvm-bridge.c\\n\");\n"
"        return 1;\n"
"    }\n"
"\n"
"    char* program_obj = compiler_temp_obj_path(exe_file, \"program\");\n"
"    char* runtime_obj = compiler_temp_obj_path(exe_file, \"runtime\");\n"
"    char* bridge_obj = compiler_temp_obj_path(exe_file, \"bridge\");\n"
"\n"
"    char* q_ir = quote_arg(ir_file);\n"
"    char* q_exe = quote_arg(exe_file);\n"
"    char* q_program_obj = quote_arg(program_obj);\n"
"    char* q_runtime_obj = quote_arg(runtime_obj);\n"
"    char* q_bridge_obj = quote_arg(bridge_obj);\n"
"    char* q_runtime_c = quote_arg(runtime_c);\n"
"    char* q_bridge_c = quote_arg(bridge_c);\n"
"\n"
"    int command_len = (int)(strlen(q_ir) + strlen(q_exe) + strlen(q_program_obj) +\n"
"                            strlen(q_runtime_obj) + strlen(q_bridge_obj) +\n"
"                            strlen(q_runtime_c) + strlen(q_bridge_c) + 256);\n"
"    char* command = (char*)malloc(command_len);\n"
"    int result = 0;\n"
"\n"
"    snprintf(command, command_len, \"llc %s -filetype=obj -o %s\", q_ir, q_program_obj);\n"
"    if (run_build_command(command) != 0) result = 1;\n"
"\n"
"    if (result == 0) {\n"
"        snprintf(command, command_len, \"clang -Wno-deprecated-declarations -c %s -o %s\", q_runtime_c, q_runtime_obj);\n"
"        if (run_build_command(command) != 0) result = 1;\n"
"    }\n"
"\n"
"    if (result == 0) {\n"
"        snprintf(command, command_len, \"clang -Wno-deprecated-declarations -c %s -o %s\", q_bridge_c, q_bridge_obj);\n"
"        if (run_build_command(command) != 0) result = 1;\n"
"    }\n"
"\n"
"    if (result == 0) {\n"
"        snprintf(command, command_len, \"clang %s %s %s -o %s\",\n"
"                 q_program_obj, q_runtime_obj, q_bridge_obj, q_exe);\n"
"        if (run_build_command(command) != 0) result = 1;\n"
"    }\n"
"\n"
"    delete_file(program_obj);\n"
"    delete_file(runtime_obj);\n"
"    delete_file(bridge_obj);\n"
"    if (embedded_runtime_c) delete_file(embedded_runtime_c);\n"
"    if (embedded_bridge_c) delete_file(embedded_bridge_c);\n"
"    if (embedded_header) delete_file(embedded_header);\n"
"    if (embedded_dir) PRISMIO_RMDIR(embedded_dir);\n"
"\n"
"    free(command);\n"
"    free(q_ir);\n"
"    free(q_exe);\n"
"    free(q_program_obj);\n"
"    free(q_runtime_obj);\n"
"    free(q_bridge_obj);\n"
"    free(q_runtime_c);\n"
"    free(q_bridge_c);\n"
"    free(program_obj);\n"
"    free(runtime_obj);\n"
"    free(bridge_obj);\n"
"    if (embedded_runtime_c) free(embedded_runtime_c);\n"
"    if (embedded_bridge_c) free(embedded_bridge_c);\n"
"    if (embedded_header) free(embedded_header);\n"
"    if (embedded_dir) free(embedded_dir);\n"
"\n"
"    return result;\n"
"}\n"
"\n"
"int compiler_run_executable(const char* exe_file) {\n"
"    char* q_exe = quote_arg(exe_file);\n"
"    int command_len = (int)strlen(q_exe) + 8;\n"
"    char* command = (char*)malloc(command_len);\n"
"\n"
"    snprintf(command, command_len, \"%s\", q_exe);\n"
"    int result = run_build_command(command);\n"
"\n"
"    free(command);\n"
"    free(q_exe);\n"
"    return result;\n"
"}\n"
"\n"
"int cli_arg_count() {\n"
"#ifdef _WIN32\n"
"    return __argc;\n"
"#else\n"
"    return 0;\n"
"#endif\n"
"}\n"
"\n"
"char* cli_arg(int index) {\n"
"#ifdef _WIN32\n"
"    if (index < 0 || index >= __argc) {\n"
"        return \"\";\n"
"    }\n"
"    return __argv[index];\n"
"#else\n"
"    return \"\";\n"
"#endif\n"
"}\n"
"\n"
"// Helpers for type punning ASTNode pointers in Prismio\n"
"void* ptr_to_node(void* ptr) { return ptr; }\n"
"void* node_to_ptr(void* ptr) { return ptr; }\n"
"void* ptr_to_token(void* ptr) { return ptr; }\n"
"void* token_to_ptr(void* ptr) { return ptr; }\n"
;

static const char prismio_embedded_llvm_bridge_c[] =
"// ============================================\n"
"// String-Based LLVM IR Generator for Prismio\n"
"// No LLVM dependencies - generates IR as text\n"
"// ============================================\n"
"\n"
"#include <stdio.h>\n"
"#include <stdlib.h>\n"
"#include <string.h>\n"
"\n"
"// ============================================\n"
"// Global State\n"
"// ============================================\n"
"\n"
"#define MAX_IR_SIZE 8388608\n"
"#define MAX_FUNCTION_BODY_SIZE 2097152\n"
"#define MAX_FUNCTION_ALLOCA_SIZE 262144\n"
"#define MAX_LABEL_COUNT 10000\n"
"\n"
"static char ir_buffer[MAX_IR_SIZE];\n"
"static int ir_position = 0;\n"
"static char function_body_buffer[MAX_FUNCTION_BODY_SIZE];\n"
"static int function_body_position = 0;\n"
"static char function_alloca_buffer[MAX_FUNCTION_ALLOCA_SIZE];\n"
"static int function_alloca_position = 0;\n"
"static int collecting_function_body = 0;\n"
"static int next_temp = 0;\n"
"static int next_label = 0;\n"
"static FILE* output_file = NULL;\n"
"\n"
"// Type representations (as strings)\n"
"static const char* TYPE_VOID = \"void\";\n"
"static const char* TYPE_I1 = \"i1\";\n"
"static const char* TYPE_I8 = \"i8\";\n"
"static const char* TYPE_I32 = \"i32\";\n"
"static const char* TYPE_I64 = \"i64\";\n"
"static const char* TYPE_I8_PTR = \"i8*\";\n"
"\n"
"// ============================================\n"
"// Buffer Management\n"
"// ============================================\n"
"\n"
"void ir_reset() {\n"
"    ir_position = 0;\n"
"    next_temp = 0;\n"
"    next_label = 0;\n"
"    memset(ir_buffer, 0, MAX_IR_SIZE);\n"
"    memset(function_body_buffer, 0, MAX_FUNCTION_BODY_SIZE);\n"
"    memset(function_alloca_buffer, 0, MAX_FUNCTION_ALLOCA_SIZE);\n"
"    function_body_position = 0;\n"
"    function_alloca_position = 0;\n"
"    collecting_function_body = 0;\n"
"}\n"
"\n"
"static void append_to_buffer(char* buffer, int* position, int max_size, const char* str) {\n"
"    int len = strlen(str);\n"
"    if (*position + len < max_size) {\n"
"        strcpy(buffer + *position, str);\n"
"        *position += len;\n"
"    }\n"
"}\n"
"\n"
"void ir_append(const char* str) {\n"
"    if (collecting_function_body) {\n"
"        append_to_buffer(function_body_buffer, &function_body_position, MAX_FUNCTION_BODY_SIZE, str);\n"
"    } else {\n"
"        append_to_buffer(ir_buffer, &ir_position, MAX_IR_SIZE, str);\n"
"    }\n"
"}\n"
"\n"
"void ir_append_line(const char* str) {\n"
"    ir_append(str);\n"
"    ir_append(\"\\n\");\n"
"}\n"
"\n"
"static void ir_append_alloca_line(const char* str) {\n"
"    append_to_buffer(function_alloca_buffer, &function_alloca_position, MAX_FUNCTION_ALLOCA_SIZE, str);\n"
"    append_to_buffer(function_alloca_buffer, &function_alloca_position, MAX_FUNCTION_ALLOCA_SIZE, \"\\n\");\n"
"}\n"
"\n"
"const char* ir_get_buffer() {\n"
"    return ir_buffer;\n"
"}\n"
"\n"
"int ir_get_temp() {\n"
"    return next_temp++;\n"
"}\n"
"\n"
"int ir_get_label() {\n"
"    return next_label++;\n"
"}\n"
"\n"
"// ============================================\n"
"// File Operations\n"
"// ============================================\n"
"\n"
"void ir_open_file(const char* filename) {\n"
"    output_file = fopen(filename, \"w\");\n"
"}\n"
"\n"
"void ir_close_file() {\n"
"    if (output_file) {\n"
"        fclose(output_file);\n"
"        output_file = NULL;\n"
"    }\n"
"}\n"
"\n"
"void ir_write_to_file() {\n"
"    if (output_file) {\n"
"        fprintf(output_file, \"%s\", ir_buffer);\n"
"    }\n"
"}\n"
"\n"
"void ir_flush() {\n"
"    if (output_file) {\n"
"        ir_write_to_file();\n"
"        fflush(output_file);\n"
"    }\n"
"}\n"
"\n"
"// ============================================\n"
"// Module Management\n"
"// ============================================\n"
"\n"
"void ir_module_start(const char* module_name) {\n"
"    ir_reset();\n"
"\n"
"    // Add module header comments\n"
"    ir_append(\"; ModuleID = '\");\n"
"    ir_append(module_name);\n"
"    ir_append_line(\"'\");\n"
"    ir_append_line(\"source_filename = \\\"prismio_generated\\\"\");\n"
"    ir_append_line(\"target datalayout = \\\"e-m:w-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128\\\"\");\n"
"    ir_append_line(\"target triple = \\\"x86_64-pc-windows-msvc\\\"\");\n"
"    ir_append_line(\"\");\n"
"}\n"
"\n"
"void ir_module_end() {\n"
"    // Nothing special needed\n"
"}\n"
"\n"
"// ============================================\n"
"// Type Helpers\n"
"// ============================================\n"
"\n"
"const char* ir_type_void() { return TYPE_VOID; }\n"
"const char* ir_type_i1() { return TYPE_I1; }\n"
"const char* ir_type_i8() { return TYPE_I8; }\n"
"const char* ir_type_i32() { return TYPE_I32; }\n"
"const char* ir_type_i64() { return TYPE_I64; }\n"
"const char* ir_type_i8_ptr() { return TYPE_I8_PTR; }\n"
"\n"
"// Store pointer type as string (caller must manage memory)\n"
"void ir_type_pointer(const char* element_type, char* out_buffer) {\n"
"    sprintf(out_buffer, \"%s*\", element_type);\n"
"}\n"
"\n"
"void ir_type_array(const char* element_type, int count, char* out_buffer) {\n"
"    sprintf(out_buffer, \"[%d x %s]\", count, element_type);\n"
"}\n"
"\n"
"// ============================================\n"
"// ============================================\n"
"// State-Machine Builders (Array-free for FFI)\n"
"// ============================================\n"
"\n"
"static int sm_param_count = 0;\n"
"static char sm_alloca_names[512][64];\n"
"static int sm_alloca_count = 0;\n"
"\n"
"void ir_declare_function_begin(const char* name, const char* return_type) {\n"
"    ir_append(\"declare \");\n"
"    ir_append(return_type);\n"
"    ir_append(\" @\");\n"
"    ir_append(name);\n"
"    ir_append(\"(\");\n"
"    sm_param_count = 0;\n"
"}\n"
"\n"
"void ir_declare_function_param(const char* param_type) {\n"
"    if (sm_param_count > 0) ir_append(\", \");\n"
"    ir_append(param_type);\n"
"    sm_param_count++;\n"
"}\n"
"\n"
"void ir_declare_function_end() {\n"
"    ir_append_line(\")\");\n"
"}\n"
"\n"
"void ir_function_begin(const char* name, const char* return_type) {\n"
"    ir_append(\"define \");\n"
"    ir_append(return_type);\n"
"    ir_append(\" @\");\n"
"    ir_append(name);\n"
"    ir_append(\"(\");\n"
"    sm_param_count = 0;\n"
"}\n"
"\n"
"void ir_function_param(const char* param_type, const char* param_name) {\n"
"    if (sm_param_count > 0) ir_append(\", \");\n"
"    ir_append(param_type);\n"
"    ir_append(\" %\");\n"
"    ir_append(param_name);\n"
"    sm_param_count++;\n"
"}\n"
"\n"
"void ir_function_body_start() {\n"
"    ir_append_line(\") {\");\n"
"    memset(function_body_buffer, 0, MAX_FUNCTION_BODY_SIZE);\n"
"    memset(function_alloca_buffer, 0, MAX_FUNCTION_ALLOCA_SIZE);\n"
"    function_body_position = 0;\n"
"    function_alloca_position = 0;\n"
"    collecting_function_body = 1;\n"
"    sm_alloca_count = 0;\n"
"}\n"
"\n"
"void ir_function_end() {\n"
"    collecting_function_body = 0;\n"
"    ir_append(function_alloca_buffer);\n"
"    ir_append(function_body_buffer);\n"
"    ir_append_line(\"}\");\n"
"    ir_append_line(\"\");\n"
"}\n"
"\n"
"// Call Builder\n"
"static char sm_call_buffer[1024];\n"
"static int sm_call_arg_count = 0;\n"
"static char sm_call_buffer_stack[64][1024];\n"
"static int sm_call_arg_count_stack[64];\n"
"static int sm_call_stack_depth = 0;\n"
"\n"
"void ir_call_begin() {\n"
"    if (sm_call_stack_depth < 64) {\n"
"        strcpy(sm_call_buffer_stack[sm_call_stack_depth], sm_call_buffer);\n"
"        sm_call_arg_count_stack[sm_call_stack_depth] = sm_call_arg_count;\n"
"        sm_call_stack_depth++;\n"
"    }\n"
"    sm_call_arg_count = 0;\n"
"    sm_call_buffer[0] = '\\0';\n"
"}\n"
"\n"
"void ir_call_arg(const char* arg_type, const char* arg_value) {\n"
"    if (sm_call_arg_count > 0) strcat(sm_call_buffer, \", \");\n"
"    strcat(sm_call_buffer, arg_type);\n"
"    strcat(sm_call_buffer, \" \");\n"
"    strcat(sm_call_buffer, arg_value);\n"
"    sm_call_arg_count++;\n"
"}\n"
"\n"
"int ir_call_end(const char* return_type, const char* function_name) {\n"
"    char call_args[1024];\n"
"    strcpy(call_args, sm_call_buffer);\n"
"    if (sm_call_stack_depth > 0) {\n"
"        sm_call_stack_depth--;\n"
"        strcpy(sm_call_buffer, sm_call_buffer_stack[sm_call_stack_depth]);\n"
"        sm_call_arg_count = sm_call_arg_count_stack[sm_call_stack_depth];\n"
"    } else {\n"
"        sm_call_arg_count = 0;\n"
"        sm_call_buffer[0] = '\\0';\n"
"    }\n"
"\n"
"    if (strcmp(return_type, \"void\") == 0 || strcmp(return_type, \"\") == 0) {\n"
"        char buf[1024 + 256];\n"
"        sprintf(buf, \"  call void @%s(%s)\", function_name, call_args);\n"
"        ir_append_line(buf);\n"
"        return -1;\n"
"    } else {\n"
"        int temp = ir_get_temp();\n"
"        char buf[1024 + 256];\n"
"        sprintf(buf, \"  %%t%d = call %s @%s(%s)\", temp, return_type, function_name, call_args);\n"
"        ir_append_line(buf);\n"
"        return temp;\n"
"    }\n"
"}\n"
"\n"
"\n"
"// ============================================\n"
"// Basic Blocks\n"
"// ============================================\n"
"\n"
"void ir_label(const char* label_name) {\n"
"    ir_append(label_name);\n"
"    ir_append_line(\":\");\n"
"}\n"
"\n"
"void ir_label_numbered(int label_num) {\n"
"    char buffer[64];\n"
"    sprintf(buffer, \"label_%d:\", label_num);\n"
"    ir_append_line(buffer);\n"
"}\n"
"\n"
"// ============================================\n"
"// Memory Instructions\n"
"// ============================================\n"
"\n"
"int ir_alloca(const char* type, const char* name) {\n"
"    for (int i = 0; i < sm_alloca_count; i++) {\n"
"        if (strcmp(sm_alloca_names[i], name) == 0) {\n"
"            return -1;\n"
"        }\n"
"    }\n"
"\n"
"    if (sm_alloca_count < 512) {\n"
"        strncpy(sm_alloca_names[sm_alloca_count], name, 63);\n"
"        sm_alloca_names[sm_alloca_count][63] = '\\0';\n"
"        sm_alloca_count++;\n"
"    }\n"
"\n"
"    int temp = ir_get_temp();\n"
"    char buffer[256];\n"
"    sprintf(buffer, \"  %%%s = alloca %s\", name, type);\n"
"    if (collecting_function_body) {\n"
"        ir_append_alloca_line(buffer);\n"
"    } else {\n"
"        ir_append_line(buffer);\n"
"    }\n"
"    return temp;\n"
"}\n"
"\n"
"int ir_load(const char* type, const char* ptr_name) {\n"
"    int temp = ir_get_temp();\n"
"    char buffer[256];\n"
"    sprintf(buffer, \"  %%t%d = load %s, ptr %%%s\", temp, type, ptr_name);\n"
"    ir_append_line(buffer);\n"
"    return temp;\n"
"}\n"
"\n"
"void ir_store(const char* type, const char* value, const char* ptr_name) {\n"
"    char buffer[256];\n"
"    sprintf(buffer, \"  store %s %s, ptr %%%s\", type, value, ptr_name);\n"
"    ir_append_line(buffer);\n"
"}\n"
"\n"
"int ir_load_global(const char* type, const char* name) {\n"
"    int temp = ir_get_temp();\n"
"    char buffer[256];\n"
"    sprintf(buffer, \"  %%t%d = load %s, ptr @%s\", temp, type, name);\n"
"    ir_append_line(buffer);\n"
"    return temp;\n"
"}\n"
"\n"
"void ir_store_global(const char* type, const char* value, const char* name) {\n"
"    char buffer[256];\n"
"    sprintf(buffer, \"  store %s %s, ptr @%s\", type, value, name);\n"
"    ir_append_line(buffer);\n"
"}\n"
"\n"
"// ============================================\n"
"// Arithmetic Instructions\n"
"// ============================================\n"
"\n"
"int ir_add(const char* type, const char* lhs, const char* rhs) {\n"
"    int temp = ir_get_temp();\n"
"    char buffer[256];\n"
"    sprintf(buffer, \"  %%t%d = add %s %s, %s\", temp, type, lhs, rhs);\n"
"    ir_append_line(buffer);\n"
"    return temp;\n"
"}\n"
"\n"
"int ir_sub(const char* type, const char* lhs, const char* rhs) {\n"
"    int temp = ir_get_temp();\n"
"    char buffer[256];\n"
"    sprintf(buffer, \"  %%t%d = sub %s %s, %s\", temp, type, lhs, rhs);\n"
"    ir_append_line(buffer);\n"
"    return temp;\n"
"}\n"
"\n"
"int ir_mul(const char* type, const char* lhs, const char* rhs) {\n"
"    int temp = ir_get_temp();\n"
"    char buffer[256];\n"
"    sprintf(buffer, \"  %%t%d = mul %s %s, %s\", temp, type, lhs, rhs);\n"
"    ir_append_line(buffer);\n"
"    return temp;\n"
"}\n"
"\n"
"int ir_sdiv(const char* type, const char* lhs, const char* rhs) {\n"
"    int temp = ir_get_temp();\n"
"    char buffer[256];\n"
"    sprintf(buffer, \"  %%t%d = sdiv %s %s, %s\", temp, type, lhs, rhs);\n"
"    ir_append_line(buffer);\n"
"    return temp;\n"
"}\n"
"\n"
"int ir_and(const char* type, const char* lhs, const char* rhs) {\n"
"    int temp = ir_get_temp();\n"
"    char buffer[256];\n"
"    sprintf(buffer, \"  %%t%d = and %s %s, %s\", temp, type, lhs, rhs);\n"
"    ir_append_line(buffer);\n"
"    return temp;\n"
"}\n"
"\n"
"int ir_or(const char* type, const char* lhs, const char* rhs) {\n"
"    int temp = ir_get_temp();\n"
"    char buffer[256];\n"
"    sprintf(buffer, \"  %%t%d = or %s %s, %s\", temp, type, lhs, rhs);\n"
"    ir_append_line(buffer);\n"
"    return temp;\n"
"}\n"
"\n"
"int ir_srem(const char* type, const char* lhs, const char* rhs) {\n"
"    int temp = ir_get_temp();\n"
"    char buffer[256];\n"
"    sprintf(buffer, \"  %%t%d = srem %s %s, %s\", temp, type, lhs, rhs);\n"
"    ir_append_line(buffer);\n"
"    return temp;\n"
"}\n"
"\n"
"int ir_neg(const char* type, const char* value) {\n"
"    int temp = ir_get_temp();\n"
"    char buffer[256];\n"
"    sprintf(buffer, \"  %%t%d = sub %s 0, %s\", temp, type, value);\n"
"    ir_append_line(buffer);\n"
"    return temp;\n"
"}\n"
"\n"
"// ============================================\n"
"// Comparison Instructions\n"
"// ============================================\n"
"\n"
"int ir_icmp(const char* predicate, const char* type, const char* lhs, const char* rhs) {\n"
"    int temp = ir_get_temp();\n"
"    char buffer[256];\n"
"    sprintf(buffer, \"  %%t%d = icmp %s %s %s, %s\", temp, predicate, type, lhs, rhs);\n"
"    ir_append_line(buffer);\n"
"    return temp;\n"
"}\n"
"\n"
"int ir_icmp_eq(const char* type, const char* lhs, const char* rhs) {\n"
"    return ir_icmp(\"eq\", type, lhs, rhs);\n"
"}\n"
"\n"
"int ir_icmp_ne(const char* type, const char* lhs, const char* rhs) {\n"
"    return ir_icmp(\"ne\", type, lhs, rhs);\n"
"}\n"
"\n"
"int ir_icmp_slt(const char* type, const char* lhs, const char* rhs) {\n"
"    return ir_icmp(\"slt\", type, lhs, rhs);\n"
"}\n"
"\n"
"int ir_icmp_sle(const char* type, const char* lhs, const char* rhs) {\n"
"    return ir_icmp(\"sle\", type, lhs, rhs);\n"
"}\n"
"\n"
"int ir_icmp_sgt(const char* type, const char* lhs, const char* rhs) {\n"
"    return ir_icmp(\"sgt\", type, lhs, rhs);\n"
"}\n"
"\n"
"int ir_icmp_sge(const char* type, const char* lhs, const char* rhs) {\n"
"    return ir_icmp(\"sge\", type, lhs, rhs);\n"
"}\n"
"\n"
"// ============================================\n"
"// Control Flow Instructions\n"
"// ============================================\n"
"\n"
"void ir_ret(const char* type, const char* value) {\n"
"    char buffer[256];\n"
"    sprintf(buffer, \"  ret %s %s\", type, value);\n"
"    ir_append_line(buffer);\n"
"}\n"
"\n"
"void ir_ret_void() {\n"
"    ir_append_line(\"  ret void\");\n"
"}\n"
"\n"
"void ir_br(const char* label) {\n"
"    char buffer[256];\n"
"    sprintf(buffer, \"  br label %%%s\", label);\n"
"    ir_append_line(buffer);\n"
"}\n"
"\n"
"void ir_br_numbered(int label_num) {\n"
"    char buffer[256];\n"
"    sprintf(buffer, \"  br label %%label_%d\", label_num);\n"
"    ir_append_line(buffer);\n"
"}\n"
"\n"
"void ir_cond_br(const char* condition, const char* true_label, const char* false_label) {\n"
"    char buffer[256];\n"
"    sprintf(buffer, \"  br i1 %s, label %%%s, label %%%s\", condition, true_label, false_label);\n"
"    ir_append_line(buffer);\n"
"}\n"
"\n"
"void ir_cond_br_numbered(const char* condition, int true_label, int false_label) {\n"
"    char buffer[256];\n"
"    sprintf(buffer, \"  br i1 %s, label %%label_%d, label %%label_%d\",\n"
"            condition, true_label, false_label);\n"
"    ir_append_line(buffer);\n"
"}\n"
"\n"
"// ============================================\n"
"// Call Instructions\n"
"// ============================================\n"
"\n"
"int ir_call_void(const char* function_name, const char** arg_types,\n"
"                 const char** arg_values, int arg_count) {\n"
"    char buffer[512];\n"
"    sprintf(buffer, \"  call void @%s(\", function_name);\n"
"    ir_append(buffer);\n"
"\n"
"    for (int i = 0; i < arg_count; i++) {\n"
"        if (i > 0) ir_append(\", \");\n"
"        ir_append(arg_types[i]);\n"
"        ir_append(\" \");\n"
"        ir_append(arg_values[i]);\n"
"    }\n"
"\n"
"    ir_append_line(\")\");\n"
"    return -1;  // void call has no return value\n"
"}\n"
"\n"
"int ir_call(const char* return_type, const char* function_name,\n"
"            const char** arg_types, const char** arg_values, int arg_count) {\n"
"    int temp = ir_get_temp();\n"
"    char buffer[512];\n"
"    sprintf(buffer, \"  %%t%d = call %s @%s(\", temp, return_type, function_name);\n"
"    ir_append(buffer);\n"
"\n"
"    for (int i = 0; i < arg_count; i++) {\n"
"        if (i > 0) ir_append(\", \");\n"
"        ir_append(arg_types[i]);\n"
"        ir_append(\" \");\n"
"        ir_append(arg_values[i]);\n"
"    }\n"
"\n"
"    ir_append_line(\")\");\n"
"    return temp;\n"
"}\n"
"\n"
"// ============================================\n"
"// Type Conversion Instructions\n"
"// ============================================\n"
"\n"
"int ir_zext(const char* from_type, const char* value, const char* to_type) {\n"
"    int temp = ir_get_temp();\n"
"    char buffer[256];\n"
"    sprintf(buffer, \"  %%t%d = zext %s %s to %s\", temp, from_type, value, to_type);\n"
"    ir_append_line(buffer);\n"
"    return temp;\n"
"}\n"
"\n"
"int ir_sext(const char* from_type, const char* value, const char* to_type) {\n"
"    int temp = ir_get_temp();\n"
"    char buffer[256];\n"
"    sprintf(buffer, \"  %%t%d = sext %s %s to %s\", temp, from_type, value, to_type);\n"
"    ir_append_line(buffer);\n"
"    return temp;\n"
"}\n"
"\n"
"int ir_trunc(const char* from_type, const char* value, const char* to_type) {\n"
"    int temp = ir_get_temp();\n"
"    char buffer[256];\n"
"    sprintf(buffer, \"  %%t%d = trunc %s %s to %s\", temp, from_type, value, to_type);\n"
"    ir_append_line(buffer);\n"
"    return temp;\n"
"}\n"
"\n"
"int ir_bitcast(const char* from_type, const char* value, const char* to_type) {\n"
"    int temp = ir_get_temp();\n"
"    char buffer[256];\n"
"    sprintf(buffer, \"  %%t%d = bitcast %s %s to %s\", temp, from_type, value, to_type);\n"
"    ir_append_line(buffer);\n"
"    return temp;\n"
"}\n"
"\n"
"// ============================================\n"
"// Global Variables\n"
"// ============================================\n"
"\n"
"void ir_global_string(const char* name, const char* str_content) {\n"
"    int len = strlen(str_content);\n"
"    char escaped[2048];\n"
"    int out = 0;\n"
"\n"
"    for (int i = 0; str_content[i] != '\\0' && out < (int)sizeof(escaped) - 4; i++) {\n"
"        unsigned char c = (unsigned char)str_content[i];\n"
"        if (c == '\\\\') {\n"
"            escaped[out++] = '\\\\';\n"
"            escaped[out++] = '5';\n"
"            escaped[out++] = 'C';\n"
"        } else if (c == '\"') {\n"
"            escaped[out++] = '\\\\';\n"
"            escaped[out++] = '2';\n"
"            escaped[out++] = '2';\n"
"        } else if (c == '\\n') {\n"
"            escaped[out++] = '\\\\';\n"
"            escaped[out++] = '0';\n"
"            escaped[out++] = 'A';\n"
"        } else if (c == '\\r') {\n"
"            escaped[out++] = '\\\\';\n"
"            escaped[out++] = '0';\n"
"            escaped[out++] = 'D';\n"
"        } else if (c == '\\t') {\n"
"            escaped[out++] = '\\\\';\n"
"            escaped[out++] = '0';\n"
"            escaped[out++] = '9';\n"
"        } else {\n"
"            escaped[out++] = c;\n"
"        }\n"
"    }\n"
"    escaped[out] = '\\0';\n"
"\n"
"    char buffer[4096];\n"
"\n"
"    sprintf(buffer, \"@%s = private unnamed_addr constant [%d x i8] c\\\"%s\\\\00\\\"\",\n"
"            name, len + 1, escaped);\n"
"    ir_append_line(buffer);\n"
"}\n"
"\n"
"void ir_global_var(const char* name, const char* type, const char* init_value, int is_const) {\n"
"    char buffer[256];\n"
"    sprintf(buffer, \"@%s = %s global %s %s\",\n"
"            name,\n"
"            is_const ? \"constant\" : \"\",\n"
"            type,\n"
"            init_value);\n"
"    ir_append_line(buffer);\n"
"}\n"
"\n"
"const char* ir_get_temp_name(int temp_num) {\n"
"    char* result = (char*)malloc(64);\n"
"    sprintf(result, \"%%t%d\", temp_num);\n"
"    return result;\n"
"}\n"
"\n"
"const char* ir_get_label_name(int label_num) {\n"
"    char* result = (char*)malloc(64);\n"
"    sprintf(result, \"label_%d\", label_num);\n"
"    return result;\n"
"}\n"
"\n"
"// ============================================\n"
"// High-level Helper Functions\n"
"// ============================================\n"
"\n"
"void ir_comment(const char* comment) {\n"
"    ir_append(\"; \");\n"
"    ir_append_line(comment);\n"
"}\n"
"\n"
"// ============================================\n"
"// Global Variable Name Registry\n"
"// ============================================\n"
"\n"
"static char global_names[256][64];\n"
"static int global_name_count = 0;\n"
"\n"
"void ir_register_global_name(const char* name) {\n"
"    if (global_name_count < 256) {\n"
"        strncpy(global_names[global_name_count], name, 63);\n"
"        global_names[global_name_count][63] = '\\0';\n"
"        global_name_count++;\n"
"    }\n"
"}\n"
"\n"
"int ir_is_global_name(const char* name) {\n"
"    for (int i = 0; i < global_name_count; i++) {\n"
"        if (strcmp(global_names[i], name) == 0) return 1;\n"
"    }\n"
"    return 0;\n"
"}\n"
"\n"
"void ir_reset_globals() {\n"
"    global_name_count = 0;\n"
"}\n"
"\n"
"// ============================================\n"
"// Struct / Enum Type Registry\n"
"// ============================================\n"
"\n"
"typedef struct {\n"
"    char name[64];\n"
"    int field_count;\n"
"    char field_names[32][64];\n"
"    char field_types[32][64];\n"
"} StructInfo;\n"
"\n"
"static StructInfo struct_infos[128];\n"
"static int struct_info_count = 0;\n"
"\n"
"typedef struct {\n"
"    char enum_name[64];\n"
"    char variant_name[64];\n"
"    int value;\n"
"} EnumVariantInfo;\n"
"\n"
"static EnumVariantInfo enum_variants[512];\n"
"static int enum_variant_count = 0;\n"
"\n"
"void ir_reset_types() {\n"
"    struct_info_count = 0;\n"
"    enum_variant_count = 0;\n"
"}\n"
"\n"
"int ir_is_struct_type_name(const char* name) {\n"
"    for (int i = 0; i < struct_info_count; i++) {\n"
"        if (strcmp(struct_infos[i].name, name) == 0) return 1;\n"
"    }\n"
"    return 0;\n"
"}\n"
"\n"
"void ir_register_struct(const char* name) {\n"
"    if (ir_is_struct_type_name(name)) return;\n"
"    if (struct_info_count >= 128) return;\n"
"\n"
"    strncpy(struct_infos[struct_info_count].name, name, 63);\n"
"    struct_infos[struct_info_count].name[63] = '\\0';\n"
"    struct_infos[struct_info_count].field_count = 0;\n"
"    struct_info_count++;\n"
"}\n"
"\n"
"void ir_register_struct_field(const char* struct_name, const char* field_name, const char* field_type) {\n"
"    for (int i = 0; i < struct_info_count; i++) {\n"
"        if (strcmp(struct_infos[i].name, struct_name) == 0) {\n"
"            int idx = struct_infos[i].field_count;\n"
"            if (idx >= 32) return;\n"
"            strncpy(struct_infos[i].field_names[idx], field_name, 63);\n"
"            struct_infos[i].field_names[idx][63] = '\\0';\n"
"            strncpy(struct_infos[i].field_types[idx], field_type, 63);\n"
"            struct_infos[i].field_types[idx][63] = '\\0';\n"
"            struct_infos[i].field_count++;\n"
"            return;\n"
"        }\n"
"    }\n"
"}\n"
"\n"
"int ir_get_struct_field_index(const char* struct_name, const char* field_name) {\n"
"    for (int i = 0; i < struct_info_count; i++) {\n"
"        if (strcmp(struct_infos[i].name, struct_name) == 0) {\n"
"            for (int j = 0; j < struct_infos[i].field_count; j++) {\n"
"                if (strcmp(struct_infos[i].field_names[j], field_name) == 0) return j;\n"
"            }\n"
"        }\n"
"    }\n"
"    return -1;\n"
"}\n"
"\n"
"const char* ir_get_struct_field_type(const char* struct_name, const char* field_name) {\n"
"    for (int i = 0; i < struct_info_count; i++) {\n"
"        if (strcmp(struct_infos[i].name, struct_name) == 0) {\n"
"            for (int j = 0; j < struct_infos[i].field_count; j++) {\n"
"                if (strcmp(struct_infos[i].field_names[j], field_name) == 0) return struct_infos[i].field_types[j];\n"
"            }\n"
"        }\n"
"    }\n"
"    return \"i32\";\n"
"}\n"
"\n"
"void ir_register_enum_variant(const char* enum_name, const char* variant_name, int value) {\n"
"    if (enum_variant_count >= 512) return;\n"
"    strncpy(enum_variants[enum_variant_count].enum_name, enum_name, 63);\n"
"    enum_variants[enum_variant_count].enum_name[63] = '\\0';\n"
"    strncpy(enum_variants[enum_variant_count].variant_name, variant_name, 63);\n"
"    enum_variants[enum_variant_count].variant_name[63] = '\\0';\n"
"    enum_variants[enum_variant_count].value = value;\n"
"    enum_variant_count++;\n"
"}\n"
"\n"
"int ir_get_enum_variant(const char* enum_name, const char* variant_name) {\n"
"    for (int i = 0; i < enum_variant_count; i++) {\n"
"        if (strcmp(enum_variants[i].enum_name, enum_name) == 0 &&\n"
"            strcmp(enum_variants[i].variant_name, variant_name) == 0) {\n"
"            return enum_variants[i].value;\n"
"        }\n"
"    }\n"
"    return -1;\n"
"}\n"
"\n"
"// Variable Type Tracking (Symbol Table MVP)\n"
"#define MAX_VAR_TYPES 4096\n"
"static char var_types_names[MAX_VAR_TYPES][64];\n"
"static char var_types[MAX_VAR_TYPES][64];\n"
"static int var_type_count = 0;\n"
"\n"
"void ir_set_var_type(const char* name, const char* type) {\n"
"    if (var_type_count < MAX_VAR_TYPES) {\n"
"        strncpy(var_types_names[var_type_count], name, 63);\n"
"        var_types_names[var_type_count][63] = '\\0';\n"
"        strncpy(var_types[var_type_count], type, 63);\n"
"        var_types[var_type_count][63] = '\\0';\n"
"        var_type_count++;\n"
"    }\n"
"}\n"
"\n"
"const char* ir_get_var_type(const char* name) {\n"
"    // Search backwards to support variable shadowing in inner blocks\n"
"    for (int i = var_type_count - 1; i >= 0; i--) {\n"
"        if (strcmp(var_types_names[i], name) == 0) {\n"
"            return var_types[i];\n"
"        }\n"
"    }\n"
"    return \"i64\"; // Default type if unknown\n"
"}\n"
"\n"
"void ir_clear_var_types() {\n"
"    var_type_count = 0;\n"
"}\n"
"\n"
"void ir_clear_local_var_types() {\n"
"    int write = 0;\n"
"    for (int read = 0; read < var_type_count; read++) {\n"
"        if (strncmp(var_types_names[read], \"$fn$\", 4) == 0 || ir_is_global_name(var_types_names[read])) {\n"
"            if (write != read) {\n"
"                strncpy(var_types_names[write], var_types_names[read], 63);\n"
"                var_types_names[write][63] = '\\0';\n"
"                strncpy(var_types[write], var_types[read], 63);\n"
"                var_types[write][63] = '\\0';\n"
"            }\n"
"            write++;\n"
"        }\n"
"    }\n"
"    var_type_count = write;\n"
"}\n"
"\n"
"// Return tracking\n"
"static int has_returned = 0;\n"
"\n"
"void ir_set_returned() {\n"
"    has_returned = 1;\n"
"}\n"
"\n"
"int ir_has_returned() {\n"
"    return has_returned;\n"
"}\n"
"\n"
"void ir_clear_returned() {\n"
"    has_returned = 0;\n"
"}\n"
"\n"
"void ir_blank_line() {\n"
"    ir_append_line(\"\");\n"
"}\n"
"\n"
"// Print current IR buffer to stdout\n"
"void ir_print() {\n"
"    printf(\"%s\", ir_buffer);\n"
"}\n"
"\n"
"// Write IR to file and close\n"
"int ir_write_file(const char* filename) {\n"
"    ir_open_file(filename);\n"
"    if (!output_file) return 1;\n"
"\n"
"    ir_write_to_file();\n"
"    ir_close_file();\n"
"    return 0;\n"
"}\n"
"\n"
"// ============================================\n"
"// Example: Generate a simple function\n"
"// ============================================\n"
"\n"
"void ir_example_generate_add_function() {\n"
"    ir_module_start(\"example\");\n"
"\n"
"    // Function: i32 @add(i32 %a, i32 %b)\n"
"    ir_function_begin(\"add\", \"i32\");\n"
"    ir_function_param(\"i32\", \"a\");\n"
"    ir_function_param(\"i32\", \"b\");\n"
"    ir_function_body_start();\n"
"\n"
"    ir_label(\"entry\");\n"
"\n"
"    int result = ir_add(\"i32\", \"%a\", \"%b\");\n"
"\n"
"    char ret_value[32];\n"
"    sprintf(ret_value, \"%%t%d\", result);\n"
"    ir_ret(\"i32\", ret_value);\n"
"\n"
"    ir_function_end();\n"
"}\n"
;

#endif
