#!/usr/bin/env python3
"""Check that every `extern fn` has a definition in the shipped archives.

An `extern fn` is a promise that some C function exists under that exact name.
Nothing checked the promise. Six `ir_type_*` declarations sat in
`src/ir/bridge.psm` naming functions with no definition anywhere in `runtime/`
and no caller in `src/`, and they cost nothing only because nobody called them
-- the first caller would have got a link error pointing at the call site rather
than at the declaration that lied.

The instrument is the symbol table of the built archives, not a scan of the C
sources. A regex over `runtime/*.c` reports 40 undefined names, and 33 of them
are real functions generated by the `BINOP`/`CMPOP` macros in
llvm-api-backend.c. `nm` sees what the linker sees, so a macro-generated symbol
is indistinguishable from a hand-written one and the check has no false
positives to suppress.

    python tools/check_externs.py [--dist dist/Prismio]

Requires a packaged toolchain (`prismio run dist`, or build.ums's `dist`
command). Exits 0 when nothing is missing, 1 on a missing definition, and 2
when the archives are absent -- callers that run before a build can treat 2 as
"skipped" rather than as a failure.
"""
import argparse
import re
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent

# Directories whose .psm files may declare `extern fn`.
SOURCE_DIRS = ("src", "std", "ums")

# Resolved by the platform C library at link time, not by anything Prismio
# ships. Keep this list short and justified: every name here is a hole in the
# check, so a runtime symbol must never be added to it.
LIBC_SYMBOLS = {
    "exit",
}

DECL = re.compile(r"^\s*extern\s+fn\s+([A-Za-z_][A-Za-z0-9_]*)\s*\(", re.M)

# `nm` prints "<addr> <type> <name>" for a defined symbol and "<type> <name>"
# for one with no address. Lowercase types are file-local; a curated body copied
# into a program module can be static, so accept both cases.
DEFINED_TYPES = set("TDSBtdsb")


class Failure(Exception):
    pass


def declared_externs():
    """Every `extern fn` name, mapped to the places that declare it."""
    found = {}
    for directory in SOURCE_DIRS:
        root = REPO / directory
        if not root.is_dir():
            raise Failure(f"missing source directory: {directory}")
        for path in sorted(root.rglob("*.psm")):
            text = path.read_text(encoding="utf-8", errors="replace")
            for match in DECL.finditer(text):
                line = text[: match.start()].count("\n") + 1
                site = f"{path.relative_to(REPO)}:{line}"
                found.setdefault(match.group(1), []).append(site)
    return found


def archive_symbols(archives):
    """Defined symbols across the given archives, with the Mach-O underscore
    stripped so one set works on both macOS and ELF platforms."""
    defined = set()
    for archive in archives:
        result = subprocess.run(
            ["nm", "-g", str(archive)],
            capture_output=True,
            text=True,
        )
        if result.returncode != 0:
            raise Failure(
                f"nm failed on {archive.relative_to(REPO)}: {result.stderr.strip()}"
            )
        for line in result.stdout.splitlines():
            parts = line.split()
            if len(parts) >= 3 and parts[1] in DEFINED_TYPES:
                defined.add(parts[2].lstrip("_"))
            elif len(parts) == 2 and parts[0] in DEFINED_TYPES:
                defined.add(parts[1].lstrip("_"))
    return defined


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--dist",
        default="dist/Prismio",
        help="packaged toolchain holding lib/runtime.a and lib/backend.a",
    )
    args = parser.parse_args()

    lib = (REPO / args.dist) / "lib"
    archives = [lib / "runtime.a", lib / "backend.a"]
    absent = [a for a in archives if not a.exists()]
    if absent:
        names = ", ".join(str(a.relative_to(REPO)) for a in absent)
        print(f"SKIPPED: no packaged archives ({names}). Build a dist first.")
        return 2

    try:
        declared = declared_externs()
        defined = archive_symbols(archives)
    except Failure as exc:
        print(f"FAILED: {exc}")
        return 1

    missing = {
        name: sites
        for name, sites in declared.items()
        if name not in defined and name not in LIBC_SYMBOLS
    }

    if missing:
        print("`extern fn` declarations with no definition in the archives:\n")
        for name in sorted(missing):
            sites = ", ".join(missing[name])
            print(f"  {name}\n      declared at {sites}")
        print(
            "\nEach names a C function the linker cannot find. Delete the "
            "declaration, correct the spelling, or add the definition to "
            "runtime/ and re-package."
        )
        return 1

    print(
        f"Every `extern fn` has a definition "
        f"({len(declared)} declared, {len(defined)} symbols in the archives, "
        f"{len(LIBC_SYMBOLS)} resolved by libc)."
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
